<?php
/**
 * This file was generated by wCMFGenerator 2.6.1.0026 from model/requirements.xmi on 16.11.08 18:45. 
 * Manual modifications should be placed inside the protected regions.
 */
require_once(BASE."application/include/model/UseCases/class.ChiBusinessPartnerBase.php");
// PROTECTED REGION ID(application/include/model/UseCases/class.ChiBusinessPartner.php/Import) START
// PROTECTED REGION END

/**
 * @class ChiBusinessPartner
 * ChiBusinessPartner description: A ChiBusinesPartner is an external person that has a Business relation with the enterprise.
 *
 * @author Giuseppe Platania
 * @version 1.0
 */
class ChiBusinessPartner extends ChiBusinessPartnerBase
{
// PROTECTED REGION ID(application/include/model/UseCases/class.ChiBusinessPartner.php/Body) START
// PROTECTED REGION END
}
?>
