/*
 * Copyright (c) 2010 IBM. 
 * Created by the E-Energy team.
 */


/* This file was generated by ChronosGenerator version 0.9.9.5 RC2 build 0509 on 2011-03-17 18:26 */


package net.sourceforge.olympos.domain

import javax.xml.bind.annotation.XmlAccessorType
import javax.xml.bind.annotation.XmlAccessType
import javax.xml.bind.annotation.XmlElement
import javax.xml.bind.annotation.XmlType
import javax.xml.bind.annotation.XmlTransient
import javax.xml.bind.annotation.XmlID
import javax.xml.bind.annotation.XmlIDREF

/*PROTECTED REGION ID(Film<-Referenced Nodes<-uml-generatedImports) ENABLED START*/ 
/* put additional imports here */
/*PROTECTED REGION END*/

/**
 * ?
 */
@XmlAccessorType(XmlAccessType.NONE)

class Film
{
	/**
	 * ?
	 */
	@XmlElement
	
	String titel
	/**
	 * <span >this is thelengthof the movieexpressedas time (hh:mm:ss).</span><span>e.g. 02:24:12 is 2 hours, 24 minutes and 12 seconds.</span>
	 */
	@XmlElement
	
	String lenght
	/**
	 * ?
	 */
	@XmlElement
	
	String director
	/**
	 * the full name of the Country(e.g. "Germany")
	 */
	@XmlElement
	
	String nation
	/**
	 * ?
	 */
	@XmlElement
	
	String filmType
		

	/*PROTECTED REGION ID(Film<-Referenced Nodes<-uml-generatedAttributes) ENABLED START*/ 
	/* put additional attributes here */
	/*PROTECTED REGION END*/

	

	/**
	 * 
	 */
	@XmlElement
	@XmlIDREF
	InsertANewMovieWithnoncompilantAPIRequest insertANewMovieWithnoncompilantAPIRequest
	
	/**
	 * 
	 */
	@XmlElement
	@XmlIDREF
	InsertANewMovieWithnoncompilantAPIRequest insertANewMovieWithnoncompilantAPIRequest
	
	

	

	


	static mappedBy = [
		
		insertANewMovieWithnoncompilantAPIRequest: "film"		,
		insertANewMovieWithnoncompilantAPIRequest: "film"		

		/*PROTECTED REGION ID(Film<-Referenced Nodes<-uml-generatedMappedBy) ENABLED START*/ 
		/* put additional mappings here */
		/*PROTECTED REGION END*/
	]
					
	static mapping = {
		tablePerHierarchy false
		tablePerSubclass true
				

	/*PROTECTED REGION ID(Film<-Referenced Nodes<-uml-generatedMappings) ENABLED START*/ 
		/* put additional mappings here */
	/*PROTECTED REGION END*/
	}

	static constraints = {
			
			insertANewMovieWithnoncompilantAPIRequest(
				nullable: true, minSize: 1, maxSize: 1
			)
			
			insertANewMovieWithnoncompilantAPIRequest(
				nullable: true, minSize: 1, maxSize: 1
			)
			
			titel(
				nullable: true
			)
			
			lenght(
				nullable: true
			)
			
			director(
				nullable: true
			)
			
			nation(
				nullable: true
			)
			
			filmType(
				nullable: true
			)

		/*PROTECTED REGION ID(Film<-Referenced Nodes<-uml-generatedconstraints) ENABLED START*/ 
		/* put additional constraints here */
		/*PROTECTED REGION END*/
	}

	 

	/*PROTECTED REGION ID(Film<-Referenced Nodes<-uml-generatedMethods) ENABLED START*/ 
	/* put additional methods here */
	/*PROTECTED REGION END*/

}
	