/*
 * Copyright (c) 2010 IBM. 
 * Created by the E-Energy team.
 */


/* This file was generated by ChronosGenerator version 0.9.9.5 RC2 build 0509 on 2011-03-17 19:06 */


package net.sourceforge.olympos.domain

import javax.xml.bind.annotation.XmlAccessorType
import javax.xml.bind.annotation.XmlAccessType
import javax.xml.bind.annotation.XmlElement
import javax.xml.bind.annotation.XmlType
import javax.xml.bind.annotation.XmlTransient
import javax.xml.bind.annotation.XmlID
import javax.xml.bind.annotation.XmlIDREF

/*PROTECTED REGION ID(Person<-Referenced Nodes<-uml-generatedImports) ENABLED START*/ 
/* put additional imports here */
/*PROTECTED REGION END*/

/**
 * this abstract Classrepresents any Human being present in this domain.
 */
@XmlAccessorType(XmlAccessType.NONE)

class Person extends EntityBaseExtended
{
	/**
	 * ?
	 */
	@XmlElement
	
	String surname
	/**
	 * ?
	 */
	@XmlElement
	
	String birth
	/**
	 * ?
	 */
	@XmlElement
	
	String nationality
		

	/*PROTECTED REGION ID(Person<-Referenced Nodes<-uml-generatedAttributes) ENABLED START*/ 
	/* put additional attributes here */
	/*PROTECTED REGION END*/

	

	

	

	


					
	static mapping = {
		tablePerHierarchy false
		tablePerSubclass true
				

	/*PROTECTED REGION ID(Person<-Referenced Nodes<-uml-generatedMappings) ENABLED START*/ 
		/* put additional mappings here */
	/*PROTECTED REGION END*/
	}

	static constraints = {
			
			surname(
				nullable: true
			)
			
			birth(
				nullable: true
			)
			
			nationality(
				nullable: true
			)

		/*PROTECTED REGION ID(Person<-Referenced Nodes<-uml-generatedconstraints) ENABLED START*/ 
		/* put additional constraints here */
		/*PROTECTED REGION END*/
	}

	 

	/*PROTECTED REGION ID(Person<-Referenced Nodes<-uml-generatedMethods) ENABLED START*/ 
	/* put additional methods here */
	/*PROTECTED REGION END*/

}
	