
/*
 This file was generated by wCMFGenerator 2.6.1.0009 from model/helloWorld628.xmi on 09.08.08 18:46. 
  Manual modifications should be placed inside the protected regions.
   developer: Giuseppe Platania
  */
  
Ext.onReady(function(){

	Ext.QuickTips.init();
	Ext.form.Field.prototype.msgTarget = 'side';
	
	var bd = Ext.getBody();
	bd.createChild({tag: 'h2', html: 'Worker Edit View'});
	
	var form = new Ext.FormPanel({

	labelWidth: 150,
	url:'',
	frame:true,
    title: 'Edit Form',
    bodyStyle:'padding:5px 5px 0',
    width: 500,
    defaults: {width: 230},
    defaultType: 'textfield',
	items: [				
			{	
			fieldLabel: 'id',
	        name: 'id',
	        allowBlank:false,
	        inputType:'textfield',},
			{	
			fieldLabel: 'fk_enterprise_id',
	        name: 'fk_enterprise_id',
	        allowBlank:false,
	        inputType:'textfield',},
			{	
			fieldLabel: 'Name',
	        name: 'Name',
	        allowBlank:false,
	        inputType:'textfield',},
			{	
			fieldLabel: 'Role',
	        name: 'Role',
	        allowBlank:false,
	        inputType:'textfield',},

		
 			],
		buttons: [{
	        text: 'Save',
	        	handler:function() {
      				form.getForm().submit({
      				url:'main.php',
      				method: 'POST',
      				success:function(form, action) {
          				alert('Success: ' + action.response.responseText);
        			},
        			failure:function(form, action) {
          				alert('Failure: ' + action.failureType);
        		}
      });
    }
	    },{
	        text: 'Cancel',
	        	handler:function() {
      				form.getForm().reset();
    			}
	    }]
	});
	
	form.render(document.body);
});
