<?php
/*
 * Copyright (c) 2009 The Olympos Development Team.
 * 
 * http://sourceforge.net/projects/olympos/
 * 
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html. If redistributing this code,
 * this entire header must remain intact.
 */

/**
 * This file was generated by wCMFGenerator 3 from example-data/wcmf/requirements.uml on 2009-05-18 13:16. 
 * Manual modifications should be placed inside the protected regions.
 */
 require_once(BASE."wcmf/lib/presentation/class.Controller.php");
// PROTECTED REGION ID(application/include/controller/class.UWMExporterController.php/Import) ENABLED START
require_once (BASE.'wcmf/lib/persistence/class.PersistenceFacade.php');

require_once ('class.OawUtil.php');
require_once ('class.UwmUtil.php');
require_once ('class.ExportShutdownHandler.php');
// PROTECTED REGION END

/**
 * @class UWMExporterController
 * @ingroup Controller
 * @brief Generates UML out of the passed model, and returns the UML file. 
 * 
 * <b>Input actions:</b>
 * - @em exportUWM Generates and returns a UML file.
 * 
 * <b>Output actions:</b>
 * - @em failure If a fatal error occurs
 * 
 * @param[in] startModel The OID of the model to generate UML for.
 * @param[in] startPackage The OID of the package to generate UML for.
 * 
 * @author Niko &lt;enikao@users.sourceforge.net&gt;
 * 
 * The following configuration settings are defined for this controller:
 *
 * [actionmapping]
 * ??exportUWM = UWMExporterController
 *
 * [views]
 * 
 * @author 
 * @version 1.0
 */
class UWMExporterController extends Controller
{
// PROTECTED REGION ID(application/include/controller/class.UWMExporterController.php/Body) ENABLED START
	
	const SHUTDOWN_ERROR_VARIABLE = 'UwmExporterControllerError';

	private $lastTime = 0;

	private function check($msg)
	{
		$newTime = microtime(true);
	
		//echo $newTime - $this->lastTime, ": $msg<br/ >";
		
		$this->lastTime = $newTime;
	}

	public function execute()
	{
		$this->check("start");
	
		$tmpUwmExportPath = OawUtil::tempName();
	
		$startModel = $this->_request->getValue('startModel');
		$startPackage = $this->_request->getValue('startPackage');
	
		UwmUtil::exportXml($tmpUwmExportPath, $startModel, $startPackage);
	
		$tmpUmlPath = OawUtil::tempName();
	
		$tmpPropertiesPath = OawUtil::createPropertyFile('file://'.$tmpUwmExportPath, $tmpUmlPath);
	
		
		mkdir($tmpUmlPath);
	
		$this->check("start generator");
	
		$runCfg = OawUtil::runOaw($tmpPropertiesPath, 'cartridge/UmlConnector/workflow/cwm2uml.oaw');
	
		$this->check('Generator finished');
	
		$exportFile = "$tmpUmlPath/uml-generated.uml";
	
		if (filesize($exportFile) == 0) {
			$this->check('Zero return file size');
		
			return false;
		}
	
		//header('Content-type: text/plain');
		header('Content-type: application/octet-stream');
		header('Content-Disposition: attachment; filename="cwm-export.uml"');
	
		readfile($exportFile);
		//readfile($tmpUwmExportPath);
		
		$this->check('File written to output');
	
		unlink($tmpUwmExportPath);
		unlink($tmpPropertiesPath);
		unlink($exportFile);
		rmdir($tmpUmlPath);
	
		ExportShutdownHandler::success();
	
		$this->check("finished");
	
		return false;
	}

	/**
	 * @see Controller::hasView()
	 */
	function hasView()
	{
		return false;
	}

	/**
	 * @see Controller::executeKernel()
	 */
	function executeKernel()
	{
		return true;
	}

	// PROTECTED REGION END

}
?>
