<?php
/*
 * Copyright (c) 2009 The Olympos Development Team.
 * 
 * http://sourceforge.net/projects/olympos/
 * 
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html. If redistributing this code,
 * this entire header must remain intact.
 */

/**
 * This file was generated by wCMFGenerator 3.0.0018 from requirements.uml on Mon Jan 10 18:22:32 CET 2011. 
 * Manual modifications should be placed inside the protected regions.
 */
require_once(BASE."application/include/model/requirements/class.ChiFeatureStatusBase.php");
// PROTECTED REGION ID(application/include/model/requirements/class.ChiFeatureStatus.php/Import) ENABLED START
// PROTECTED REGION END

/**
 * @class ChiFeatureStatus
 * ChiFeatureStatus description: 
 *
 * @author 
 * @version 1.0
 */
class ChiFeatureStatus extends ChiFeatureStatusBase
{
// PROTECTED REGION ID(application/include/model/requirements/class.ChiFeatureStatus.php/Body) ENABLED START
// PROTECTED REGION END
}
?>
