<?php
/**
 * This file was generated by wCMFGenerator 3.0.0017 from requirements.uml on Thu Jul 02 09:52:11 CEST 2009. 
 * Manual modifications should be placed inside the protected regions.
 */
require_once(BASE."application/include/model/activity/class.ChiObjectBase.php");
// PROTECTED REGION ID(application/include/model/activity/class.ChiObject.php/Import) ENABLED START
// PROTECTED REGION END

/**
 * @class ChiObject
 * ChiObject description: a chiObject reppresent an instance of a ChiNode or a Chivalue.
 *
 * @author 
 * @version 1.0
 */
class ChiObject extends ChiObjectBase
{
// PROTECTED REGION ID(application/include/model/activity/class.ChiObject.php/Body) ENABLED START
// PROTECTED REGION END
}
?>
