<?php
/*
 * Copyright (c) 2009 The Olympos Development Team.
 * 
 * http://sourceforge.net/projects/olympos/
 * 
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html. If redistributing this code,
 * this entire header must remain intact.
 */

/**
 * This file was generated by wCMFGenerator 3 from example-data/wcmf/requirements.uml on 2009-05-28 11:58. 
 * Manual modifications should be placed inside the protected regions.
 */
require_once(BASE."application/include/model/activity/class.ActivityReceiveBase.php");
// PROTECTED REGION ID(application/include/model/activity/class.ActivityReceive.php/Import) ENABLED START
// PROTECTED REGION END

/**
 * @class ActivityReceive
 * ActivityReceive description: this element indicates that a previous sended messages has been received.
 *
 * @author 
 * @version 1.0
 */
class ActivityReceive extends ActivityReceiveBase
{
// PROTECTED REGION ID(application/include/model/activity/class.ActivityReceive.php/Body) ENABLED START
// PROTECTED REGION END
}
?>
