<?php
/**
 * This file was generated by wCMFGenerator 2.6.1.0026 from model/requirements.xmi on 17.11.08 18:35. 
 * Manual modifications should be placed inside the protected regions.
 */
require_once(BASE."application/include/model/domain/class.ChiControllerBase.php");
// PROTECTED REGION ID(application/include/model/domain/class.ChiController.php/Import) START
// PROTECTED REGION END

/**
 * @class ChiController
 * ChiController description: 
 *
 * @author Giuseppe Platania
 * @version 1.0
 */
class ChiController extends ChiControllerBase
{
// PROTECTED REGION ID(application/include/model/domain/class.ChiController.php/Body) START
// PROTECTED REGION END
}
?>
