<?php
/**
 * This file was generated by wCMFGenerator 3 from src/model/wcmf_default.uml on Mon Apr 27 15:03:52 CEST 2009. 
 * Manual modifications should be placed inside the protected regions.
 */
require_once(BASE."application/include/model/domain/class.ChiNodeBase.php");
// PROTECTED REGION ID(application/include/model/domain/class.ChiNode.php/Import) ENABLED START
// PROTECTED REGION END

/**
 * @class ChiNode
 * ChiNode description: A Domain Object type used in Chronos. ChiNodes and ChiValues define the application data model.
 *
 * @author 
 * @version 1.0
 */
class ChiNode extends ChiNodeBase
{
// PROTECTED REGION ID(application/include/model/domain/class.ChiNode.php/Body) ENABLED START
// PROTECTED REGION END
}
?>
