<?php
/**
 * This file was generated by wCMFGenerator 3.0.0017 from requirements.uml on Mon Aug 03 13:49:05 CEST 2009. 
 * Manual modifications should be placed inside the protected regions.
 */
require_once(BASE."application/include/model/domain/class.ChiControllerActionKeyTargetBase.php");
// PROTECTED REGION ID(application/include/model/domain/class.ChiControllerActionKeyTarget.php/Import) ENABLED START
// PROTECTED REGION END

/**
 * @class ChiControllerActionKeyTarget
 * ChiControllerActionKeyTarget description: A ChiController, Views and Associations define the application flow. A controller represent the Business logic where a certain flow is physical implemented.
 *
 * @author 
 * @version 1.0
 */
class ChiControllerActionKeyTarget extends ChiControllerActionKeyTargetBase
{
// PROTECTED REGION ID(application/include/model/domain/class.ChiControllerActionKeyTarget.php/Body) ENABLED START
// PROTECTED REGION END
}
?>
