<?php
/**
 * This file was generated by wCMFGenerator 3.0.0018 from requirements.uml on Mon Mar 21 15:09:12 CET 2011. 
 * Manual modifications should be placed inside the protected regions.
 */
require_once(BASE."application/include/model/domain/class.NMChiControllerChiController.php");

/**
 * @class SourceEnd
 * SourceEnd description: this class handle all the relationships between ChiControllers.
 *
 * @author 
 * @version 1.0
 */
class SourceEndBase extends NMChiControllerChiController
{
    function SourceEndBase($oid=null, $type=null)
    {
      if ($type == null)
        parent::__construct($oid, 'SourceEnd');
      else
        parent::__construct($oid, $type);
    }
    /**
     * @see PersistentObject::getBaseType()
     */
    function getBaseType()
    {
      return "NMChiControllerChiController";
    }
    /**
     * @see PersistentObject::getObjectDisplayName()
     */
    function getObjectDisplayName()
    {
      return Message::get("SourceEnd");
    }
}
?>
