<?php
/**
 * This file was generated by wCMFGenerator 3.0.0017 from requirements.uml on Mon Aug 03 13:49:07 CEST 2009. 
 * Manual modifications should be placed inside the protected regions.
 */
require_once(BASE."application/include/model/class.PackageBase.php");
// PROTECTED REGION ID(application/include/model/class.Package.php/Import) ENABLED START
// PROTECTED REGION END

/**
 * @class Package
 * Package description: a package is a class that contains other classes including packages sef
 *
 * @author 
 * @version 1.0
 */
class Package extends PackageBase
{
// PROTECTED REGION ID(application/include/model/class.Package.php/Body) ENABLED START
// PROTECTED REGION END
}
?>
