<?php
/**
 * This file was generated by wCMFGenerator 2.6.0001 from model/requirements.xmi on 29.03.08 20:12. 
 * Manual modifications should be placed inside the protected regions.
 */
require_once(BASE."application/include/model/class.ChiFeatureStatusBase.php");
// PROTECTED REGION ID(application/include/model/class.ChiFeatureStatus.php/Import) START
// PROTECTED REGION END

/**
 * @class ChiFeatureStatus
 * ChiFeatureStatus description: 
 *
 * @author Giuseppe Platania
 * @version 1.0
 */
class ChiFeatureStatus extends ChiFeatureStatusBase
{
// PROTECTED REGION ID(application/include/model/class.ChiFeatureStatus.php/Body) START
// PROTECTED REGION END
}
?>
