/*
 *  This file was generated by wCMFGenerator 3.0.0 from src/requirements.uml on Mon Jan 12 18:09:57 CET 2009. 
  Manual modifications should be placed inside the protected regions.
 * Copyright (c) 2009 The Olympos Development Team.
 *
 * http://sourceforge.net/projects/olympos/
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html. If redistributing this code,
 * this entire header must remain intact.
 */
Ext.namespace("cwm");

cwm.AdodbseqClass = function() {
	cwm.AdodbseqClass.superclass.constructor.call(this);
	
	this.uwmClassName = "Adodbseq";
	this.instanceClassName = "cwm.Adodbseq";
	this.treeIcon = "FigureAdodbseq";
	this.figureIcon = "FigureAdodbseq";
	this.figureClass = "uwm.graphics.figure.RectangleFigure";
	this.description = " ";
	this.helpUrl = "help/index.html#Adodbseq|outline";
	this.defaultLabel = "New Adodbseq";
	this.labelProperties = {
		Name: true
	};

	this.gridTabIconClass = "AdodbseqTab";
	this.gridTabTip = "Shows all <b>Adodbseq</b> within selected scope";
	this.gridFields = [{
		name: "oid",
		mapping: "oid"
	}, {
		name: "Label",
		mapping: "Label"
	}];
	this.gridColumns = [{
		header: "Label",
		dataIndex: "Label",
		sortable: true
	}];
	
	this.connectionInfo = {
			
			, 			
	};
}

Ext.extend(cwm.AdodbseqClass, uwm.model.ModelClass);

cwm.AdodbseqClass.prototype.getPropertyForm = function(modelNode) {
	return new uwm.ui.PropertyForm({
		items: [	]
	});
}

cwm.AdodbseqClass.prototype.getGraphics = function(label, figure) {
	return new uwm.graphics.figure.ImageFigure(label, figure, "../application/images/Adodbseq.PNG", 96, 95, 96, 95);
}

uwm.model.ModelNodeClassContainer.getInstance().registerClass(new cwm.AdodbseqClass());

	