<?php
/**
 * This file was generated by wCMFGenerator 2.6.0001 from model/requirements.xmi on 29.03.08 18:02. 
 * Manual modifications should be placed inside the protected regions.
 */
require_once(BASE."application/include/model/class.ChiRequirementTypeBase.php");
// PROTECTED REGION ID(application/include/model/class.ChiRequirementType.php/Import) START
// PROTECTED REGION END

/**
 * @class ChiRequirementType
 * ChiRequirementType description: Type of requirement
 *
 * @author Giuseppe Platania
 * @version 1.0
 */
class ChiRequirementType extends ChiRequirementTypeBase
{
// PROTECTED REGION ID(application/include/model/class.ChiRequirementType.php/Body) START
// PROTECTED REGION END
}
?>
