<?php
/**
 * This file was generated by wCMFGenerator 3.0.0017 from requirements.uml on Mon Aug 03 13:49:08 CEST 2009. 
 * Manual modifications should be placed inside the protected regions.
 */
require_once(BASE."application/include/model/class.NMFiguresDiagramBase.php");
// PROTECTED REGION ID(application/include/model/class.NMFiguresDiagram.php/Import) ENABLED START
// PROTECTED REGION END

/**
 * @class NMFiguresDiagram
 * NMFiguresDiagram description: 
 *
 * @author 
 * @version 1.0
 */
class NMFiguresDiagram extends NMFiguresDiagramBase
{
// PROTECTED REGION ID(application/include/model/class.NMFiguresDiagram.php/Body) ENABLED START
// PROTECTED REGION END
}
?>
