<?php
/**
 * This file was generated by wCMFGenerator 3.0.0017 from requirements.uml on Thu Jul 30 11:28:51 CEST 2009. 
 * Manual modifications should be placed inside the protected regions.
 */
require_once(BASE."application/include/model/domain/class.InputTypeBase.php");
// PROTECTED REGION ID(application/include/model/domain/class.InputType.php/Import) ENABLED START
// PROTECTED REGION END

/**
 * @class InputType
 * InputType description: this class hosts all the allowed input types like text, password, textarea, select, radio, checkbox, file, fileex, fckeditor, filebrowser, linkbrowser, date ...
 *
 * @author 
 * @version 1.0
 */
class InputType extends InputTypeBase
{
// PROTECTED REGION ID(application/include/model/domain/class.InputType.php/Body) ENABLED START
// PROTECTED REGION END
}
?>
