<?php
/*
 * Copyright (c) 2009 The Olympos Development Team.
 * 
 * http://sourceforge.net/projects/olympos/
 * 
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html. If redistributing this code,
 * this entire header must remain intact.
 */

/**
 * This file was generated by wCMFGenerator 3.0.0017 from requirements.uml on Fri Aug 28 16:05:51 CEST 2009. 
 * Manual modifications should be placed inside the protected regions.
 */
require_once(BASE."application/include/model/domain/class.ChiClassBase.php");
// PROTECTED REGION ID(application/include/model/domain/class.ChiClass.php/Import) ENABLED START
// PROTECTED REGION END

/**
 * @class ChiClass
 * ChiClass description: this object reppresent a UML::class
 *
 * @author 
 * @version 1.0
 */
class ChiClass extends ChiClassBase
{
// PROTECTED REGION ID(application/include/model/domain/class.ChiClass.php/Body) ENABLED START
// PROTECTED REGION END
}
?>
