<?php
/**
 * This file was generated by wCMFGenerator 3.0.0017 from requirements.uml on Thu Jul 30 11:28:52 CEST 2009. 
 * Manual modifications should be placed inside the protected regions.
 */
require_once(BASE."application/include/model/activity/class.NMActivityActivityDecisionBase.php");
// PROTECTED REGION ID(application/include/model/activity/class.NMActivityActivityDecision.php/Import) ENABLED START
// PROTECTED REGION END

/**
 * @class NMActivityActivityDecision
 * NMActivityActivityDecision description: 
 *
 * @author 
 * @version 1.0
 */
class NMActivityActivityDecision extends NMActivityActivityDecisionBase
{
// PROTECTED REGION ID(application/include/model/activity/class.NMActivityActivityDecision.php/Body) ENABLED START
// PROTECTED REGION END
}
?>
