<?php
/**
 * This file was generated by wCMFGenerator 3.0.0004 from ./model/cwm.uml on Thu Feb 12 11:44:52 CET 2009. 
 * Manual modifications should be placed inside the protected regions.
 */
require_once(BASE."application/include/model/activity/class.ActivitySendBase.php");
// PROTECTED REGION ID(application/include/model/activity/class.ActivitySend.php/Import) ENABLED START
// PROTECTED REGION END

/**
 * @class ActivitySend
 * ActivitySend description: 
 *
 * @author 
 * @version 1.0
 */
class ActivitySend extends ActivitySendBase
{
// PROTECTED REGION ID(application/include/model/activity/class.ActivitySend.php/Body) ENABLED START
// PROTECTED REGION END
}
?>
