<?php
/**
 * This file was generated by wCMFGenerator 2.6.1.0012 from model/requirements.xmi on 25.08.08 19:09. 
 * Manual modifications should be placed inside the protected regions.
 */
require_once(BASE."application/include/model/wcmf/class.RoleRDBBase.php");
// PROTECTED REGION ID(application/include/model/wcmf/class.RoleRDB.php/Import) START
// PROTECTED REGION END

/**
 * @class RoleRDB
 * RoleRDB description: 
 *
 * @author <ingo@wemove.com>
 * @version 1.0
 */
class RoleRDB extends RoleRDBBase
{
// PROTECTED REGION ID(application/include/model/wcmf/class.RoleRDB.php/Body) START
// PROTECTED REGION END
}
?>
