<?php
/**
 * This file was generated by wCMFGenerator 3.0.0017 from requirements.uml on Thu Jul 30 11:28:26 CEST 2009. 
 * Manual modifications should be placed inside the protected regions.
 */
require_once(BASE."application/include/model/wcmf/class.AdodbseqBase.php");
// PROTECTED REGION ID(application/include/model/wcmf/class.Adodbseq.php/Import) ENABLED START
// PROTECTED REGION END

/**
 * @class Adodbseq
 * Adodbseq description: 
 *
 * @author 
 * @version 1.0
 */
class Adodbseq extends AdodbseqBase
{
// PROTECTED REGION ID(application/include/model/wcmf/class.Adodbseq.php/Body) ENABLED START
// PROTECTED REGION END
}
?>
