<?php
/**
 * This file was generated by wCMFGenerator 2.6.1.0019 from model/requirements.xmi on 05.09.08 11:35. 
 * Manual modifications should be placed inside the protected regions.
 */
require_once(BASE."application/include/model/wcmf/class.LocktableBase.php");
// PROTECTED REGION ID(application/include/model/wcmf/class.Locktable.php/Import) START
// PROTECTED REGION END

/**
 * @class Locktable
 * Locktable description: 
 *
 * @author <ingo@wemove.com>
 * @version 1.0
 */
class Locktable extends LocktableBase
{
// PROTECTED REGION ID(application/include/model/wcmf/class.Locktable.php/Body) START
// PROTECTED REGION END
}
?>
