<?php
/**
 * This file was generated by wCMFGenerator 2.6.1.0026 from model/requirements.xmi on 17.11.08 18:35. 
 * Manual modifications should be placed inside the protected regions.
 */
require_once(BASE."application/include/model/wcmf/class.AdodbseqBase.php");
// PROTECTED REGION ID(application/include/model/wcmf/class.Adodbseq.php/Import) START
// PROTECTED REGION END

/**
 * @class Adodbseq
 * Adodbseq description: 
 *
 * @author <ingo@wemove.com>
 * @version 1.0
 */
class Adodbseq extends AdodbseqBase
{
// PROTECTED REGION ID(application/include/model/wcmf/class.Adodbseq.php/Body) START
// PROTECTED REGION END
}
?>
