//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.09 at 03:08:38 PM MESZ 
//


package com.ibm.eenergy.common.usecases.sendreadings;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReadingKind.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ReadingKind">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="other"/>
 *     &lt;enumeration value="time"/>
 *     &lt;enumeration value="date"/>
 *     &lt;enumeration value="volume"/>
 *     &lt;enumeration value="pressure"/>
 *     &lt;enumeration value="powerFactor"/>
 *     &lt;enumeration value="phaseAngle"/>
 *     &lt;enumeration value="currentAngle"/>
 *     &lt;enumeration value="voltageAngle"/>
 *     &lt;enumeration value="current"/>
 *     &lt;enumeration value="voltage"/>
 *     &lt;enumeration value="demand"/>
 *     &lt;enumeration value="power"/>
 *     &lt;enumeration value="energy"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ReadingKind")
@XmlEnum
public enum ReadingKind {

    @XmlEnumValue("other")
    OTHER("other"),
    @XmlEnumValue("time")
    TIME("time"),
    @XmlEnumValue("date")
    DATE("date"),
    @XmlEnumValue("volume")
    VOLUME("volume"),
    @XmlEnumValue("pressure")
    PRESSURE("pressure"),
    @XmlEnumValue("powerFactor")
    POWER_FACTOR("powerFactor"),
    @XmlEnumValue("phaseAngle")
    PHASE_ANGLE("phaseAngle"),
    @XmlEnumValue("currentAngle")
    CURRENT_ANGLE("currentAngle"),
    @XmlEnumValue("voltageAngle")
    VOLTAGE_ANGLE("voltageAngle"),
    @XmlEnumValue("current")
    CURRENT("current"),
    @XmlEnumValue("voltage")
    VOLTAGE("voltage"),
    @XmlEnumValue("demand")
    DEMAND("demand"),
    @XmlEnumValue("power")
    POWER("power"),
    @XmlEnumValue("energy")
    ENERGY("energy");
    private final String value;

    ReadingKind(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ReadingKind fromValue(String v) {
        for (ReadingKind c: ReadingKind.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
