#
# This file was generated by wCMFGenerator 3.0.0017 from requirements.uml on Wed Sep 30 17:47:42 CEST 2009. 
# Manual modifications should be placed inside the protected regions.
#
#
# Structure of Table `ActivitySet`
# An activity set contains all the element owned by an activity diagramm.
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `ActivitySet`;
CREATE TABLE `ActivitySet` # entityType=ActivitySet tableId={05754823-0E5A-49ba-870D-96DCBE55430B}
(
  `id` INT(11) NOT NULL, # columnId=_i4vN-q3YEd6pn5gd7VEuBA 
  `fk_chibusinessusecasecore_id` INT(11), # columnId=_i4vN9a3YEd6pn5gd7VEuBA referencedTable=ChiBusinessUseCaseCore
  `fk_chibusinessusecase_id` INT(11), # columnId=_i4vN8K3YEd6pn5gd7VEuBA referencedTable=ChiBusinessUseCase
  `name` VARCHAR(255), # columnId=_i4SiAK3YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_i4SiB63YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_i4SiDq3YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_i4SiFa3YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_i4SiHK3YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_i4SiI63YEd6pn5gd7VEuBA 
  `sortkey` INT(11),
  PRIMARY KEY (`id`)
  ,KEY `fk_chibusinessusecasecore_id` (`fk_chibusinessusecasecore_id`)
  ,KEY `fk_chibusinessusecase_id` (`fk_chibusinessusecase_id`)
) TYPE=MyISAM;
#
# Structure of Table `ChiObject`
# a chiObject reppresent an instance of a ChiNode or a Chivalue.
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `ChiObject`;
CREATE TABLE `ChiObject` # entityType=ChiObject tableId={F1792FA4-5A7E-4820-8126-145B54CFBC05}
(
  `id` INT(11) NOT NULL, # columnId=_imj45K3YEd6pn5gd7VEuBA 
  `fk_chinodemanytomany_id` INT(11), # columnId=_imj4363YEd6pn5gd7VEuBA referencedTable=ChiNodeManyToMany
  `fk_package_id` INT(11), # columnId=_imj42q3YEd6pn5gd7VEuBA referencedTable=Package
  `fk_chinode_id` INT(11), # columnId=_imj41a3YEd6pn5gd7VEuBA referencedTable=ChiNode
  `fk_activityset_id` INT(11), # columnId=_imj40K3YEd6pn5gd7VEuBA referencedTable=ActivitySet
  `object_status` VARCHAR(255), # columnId={CD6B29F2-6303-4260-897E-4D4E60431F35} 
  `alias` VARCHAR(255), # columnId=_il-C8K3YEd6pn5gd7VEuBA 
  `status` VARCHAR(255), # columnId=_il-C963YEd6pn5gd7VEuBA 
  `author` VARCHAR(255), # columnId=_imHM4K3YEd6pn5gd7VEuBA 
  `version` VARCHAR(255), # columnId=_imHM5q3YEd6pn5gd7VEuBA 
  `name` VARCHAR(255), # columnId=_imHM7a3YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_imHM9K3YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_imHM-63YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_imHNAq3YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_imHNCa3YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_imQ95a3YEd6pn5gd7VEuBA 
  `sortkey` INT(11),
  PRIMARY KEY (`id`)
  ,KEY `fk_chinodemanytomany_id` (`fk_chinodemanytomany_id`)
  ,KEY `fk_package_id` (`fk_package_id`)
  ,KEY `fk_chinode_id` (`fk_chinode_id`)
  ,KEY `fk_activityset_id` (`fk_activityset_id`)
) TYPE=MyISAM;
#
# Structure of Table `NMActivityActivityDecision`
# 
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `NMActivityActivityDecision`;
CREATE TABLE `NMActivityActivityDecision` # entityType=NMActivityActivityDecision tableId={500759D8-C071-4e70-BDC7-893FA04E4A71}
(
  `id` INT(11) NOT NULL, # columnId=_jAoluq3YEd6pn5gd7VEuBA 
  `fk_activitydecision_id` INT(11), # columnId=_jAolta3YEd6pn5gd7VEuBA referencedTable=ActivityDecision
  `fk_activity_id` INT(11), # columnId=_jAolsK3YEd6pn5gd7VEuBA referencedTable=Activity
  PRIMARY KEY (`id`)
  ,KEY `fk_activitydecision_id` (`fk_activitydecision_id`)
  ,KEY `fk_activity_id` (`fk_activity_id`)
) TYPE=MyISAM;
#
# Structure of Table `NMActivityChiObject`
# 
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `NMActivityChiObject`;
CREATE TABLE `NMActivityChiObject` # entityType=NMActivityChiObject tableId={582AC351-7317-4967-86B2-ACF7AA22A525}
(
  `id` INT(11) NOT NULL, # columnId=_i_v06q3YEd6pn5gd7VEuBA 
  `fk_activity_id` INT(11), # columnId=_i_v05a3YEd6pn5gd7VEuBA referencedTable=Activity
  `fk_chiobject_id` INT(11), # columnId=_i_v04K3YEd6pn5gd7VEuBA referencedTable=ChiObject
  PRIMARY KEY (`id`)
  ,KEY `fk_activity_id` (`fk_activity_id`)
  ,KEY `fk_chiobject_id` (`fk_chiobject_id`)
) TYPE=MyISAM;
#
# Structure of Table `Activity`
# An activity is the specification of a parameterized sequence of behaviour. An activity is shown as a round-cornered rectangle enclosing all the actions, control flows and other elements that make up the activity.
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `Activity`;
CREATE TABLE `Activity` # entityType=Activity tableId={409978A0-453D-48d2-BBA7-F131C49A09A0}
(
  `id` INT(11) NOT NULL, # columnId=_ilhXGa3YEd6pn5gd7VEuBA 
  `fk_package_id` INT(11), # columnId=_ilhXFK3YEd6pn5gd7VEuBA referencedTable=Package
  `fk_activityinitial_id` INT(11), # columnId=_ilhXD63YEd6pn5gd7VEuBA referencedTable=ActivityInitial
  `fk_activityreceive_id` INT(11), # columnId=_ilhXCq3YEd6pn5gd7VEuBA referencedTable=ActivityReceive
  `fk_activity_id` INT(11), # columnId=_ilhXBa3YEd6pn5gd7VEuBA referencedTable=Activity
  `fk_activityset_id` INT(11), # columnId=_ilhXAK3YEd6pn5gd7VEuBA referencedTable=ActivitySet
  `alias` VARCHAR(255), # columnId=_ik66EK3YEd6pn5gd7VEuBA 
  `status` VARCHAR(255), # columnId=_ik66F63YEd6pn5gd7VEuBA 
  `author` VARCHAR(255), # columnId=_ilErFK3YEd6pn5gd7VEuBA 
  `version` VARCHAR(255), # columnId=_ilErGq3YEd6pn5gd7VEuBA 
  `name` VARCHAR(255), # columnId=_ilErIa3YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_ilErKK3YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_ilErL63YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_ilErNq3YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_ilErPa3YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_ilN1Bq3YEd6pn5gd7VEuBA 
  `sortkey` INT(11),
  PRIMARY KEY (`id`)
  ,KEY `fk_package_id` (`fk_package_id`)
  ,KEY `fk_activityinitial_id` (`fk_activityinitial_id`)
  ,KEY `fk_activityreceive_id` (`fk_activityreceive_id`)
  ,KEY `fk_activity_id` (`fk_activity_id`)
  ,KEY `fk_activityset_id` (`fk_activityset_id`)
) TYPE=MyISAM;
#
# Structure of Table `ActivityDecision`
# A Decision is used to represent a choice amongst several possibilities.  Each transition usually is labeled with a text describing the response to the question posed by the Decision point.
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `ActivityDecision`;
CREATE TABLE `ActivityDecision` # entityType=ActivityDecision tableId={31C3DADE-78D2-4088-A37A-658BB11076D8}
(
  `id` INT(11) NOT NULL, # columnId=_ikeOKq3YEd6pn5gd7VEuBA 
  `fk_package_id` INT(11), # columnId=_ikeOJa3YEd6pn5gd7VEuBA referencedTable=Package
  `fk_activityset_id` INT(11), # columnId=_ikeOIK3YEd6pn5gd7VEuBA referencedTable=ActivitySet
  `alias` VARCHAR(255), # columnId=_ij4YQK3YEd6pn5gd7VEuBA 
  `status` VARCHAR(255), # columnId=_ikBiNa3YEd6pn5gd7VEuBA 
  `author` VARCHAR(255), # columnId=_ikBiO63YEd6pn5gd7VEuBA 
  `version` VARCHAR(255), # columnId=_ikBiQa3YEd6pn5gd7VEuBA 
  `name` VARCHAR(255), # columnId=_ikBiSK3YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_ikBiT63YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_ikLTNq3YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_ikLTPa3YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_ikLTRK3YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_ikLTS63YEd6pn5gd7VEuBA 
  `sortkey` INT(11),
  PRIMARY KEY (`id`)
  ,KEY `fk_package_id` (`fk_package_id`)
  ,KEY `fk_activityset_id` (`fk_activityset_id`)
) TYPE=MyISAM;
#
# Structure of Table `ActivityReceive`
# this element indicates that a previous sended messages has been received.
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `ActivityReceive`;
CREATE TABLE `ActivityReceive` # entityType=ActivityReceive tableId={620EF852-0424-428f-BF11-308F612AC86C}
(
  `id` INT(11) NOT NULL, # columnId=_ijldX63YEd6pn5gd7VEuBA 
  `fk_package_id` INT(11), # columnId=_ijldWq3YEd6pn5gd7VEuBA referencedTable=Package
  `fk_activitysend_id` INT(11), # columnId=_ijldVa3YEd6pn5gd7VEuBA referencedTable=ActivitySend
  `fk_activityset_id` INT(11), # columnId=_ijldUK3YEd6pn5gd7VEuBA referencedTable=ActivitySet
  `alias` VARCHAR(255), # columnId=_ii_AYK3YEd6pn5gd7VEuBA 
  `status` VARCHAR(255), # columnId=_ii_AZ63YEd6pn5gd7VEuBA 
  `author` VARCHAR(255), # columnId=_ii_Aba3YEd6pn5gd7VEuBA 
  `version` VARCHAR(255), # columnId=_ijIxZK3YEd6pn5gd7VEuBA 
  `name` VARCHAR(255), # columnId=_ijIxa63YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_ijIxcq3YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_ijIxea3YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_ijIxgK3YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_ijIxh63YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_ijIxjq3YEd6pn5gd7VEuBA 
  `sortkey` INT(11),
  PRIMARY KEY (`id`)
  ,KEY `fk_package_id` (`fk_package_id`)
  ,KEY `fk_activitysend_id` (`fk_activitysend_id`)
  ,KEY `fk_activityset_id` (`fk_activityset_id`)
) TYPE=MyISAM;
#
# Structure of Table `ActivitySend`
# This eslement indicates the sending of a message.
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `ActivitySend`;
CREATE TABLE `ActivitySend` # entityType=ActivitySend tableId={2A96B8F4-371B-4a95-A143-2256DE4A9878}
(
  `id` INT(11) NOT NULL, # columnId=_iiiUf63YEd6pn5gd7VEuBA 
  `fk_package_id` INT(11), # columnId=_iiiUeq3YEd6pn5gd7VEuBA referencedTable=Package
  `fk_activity_id` INT(11), # columnId=_iiiUda3YEd6pn5gd7VEuBA referencedTable=Activity
  `fk_activityset_id` INT(11), # columnId=_iiiUcK3YEd6pn5gd7VEuBA referencedTable=ActivitySet
  `alias` VARCHAR(255), # columnId=_ih8ekK3YEd6pn5gd7VEuBA 
  `status` VARCHAR(255), # columnId=_iiFoha3YEd6pn5gd7VEuBA 
  `author` VARCHAR(255), # columnId=_iiFoi63YEd6pn5gd7VEuBA 
  `version` VARCHAR(255), # columnId=_iiFoka3YEd6pn5gd7VEuBA 
  `name` VARCHAR(255), # columnId=_iiFomK3YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_iiFon63YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_iiPZgK3YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_iiPZh63YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_iiPZjq3YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_iiPZla3YEd6pn5gd7VEuBA 
  `sortkey` INT(11),
  PRIMARY KEY (`id`)
  ,KEY `fk_package_id` (`fk_package_id`)
  ,KEY `fk_activity_id` (`fk_activity_id`)
  ,KEY `fk_activityset_id` (`fk_activityset_id`)
) TYPE=MyISAM;
#
# Structure of Table `ActivityInitial`
# An initial or start node is depicted by a large black spot.
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `ActivityInitial`;
CREATE TABLE `ActivityInitial` # entityType=ActivityInitial tableId={0BA733C1-27BB-4491-AB53-B2E47EA311C9}
(
  `id` INT(11) NOT NULL, # columnId=_iho8mq3YEd6pn5gd7VEuBA 
  `fk_package_id` INT(11), # columnId=_iho8la3YEd6pn5gd7VEuBA referencedTable=Package
  `fk_activityset_id` INT(11), # columnId=_iho8kK3YEd6pn5gd7VEuBA referencedTable=ActivitySet
  `alias` VARCHAR(255), # columnId=_ihDGsK3YEd6pn5gd7VEuBA 
  `status` VARCHAR(255), # columnId=_ihDGt63YEd6pn5gd7VEuBA 
  `author` VARCHAR(255), # columnId=_ihDGva3YEd6pn5gd7VEuBA 
  `version` VARCHAR(255), # columnId=_ihM3tK3YEd6pn5gd7VEuBA 
  `name` VARCHAR(255), # columnId=_ihM3u63YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_ihM3wq3YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_ihM3ya3YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_ihM30K3YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_ihM3163YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_ihWBpa3YEd6pn5gd7VEuBA 
  `sortkey` INT(11),
  PRIMARY KEY (`id`)
  ,KEY `fk_package_id` (`fk_package_id`)
  ,KEY `fk_activityset_id` (`fk_activityset_id`)
) TYPE=MyISAM;
#
# Structure of Table `ActivityFinal`
# An final t node is depicted by a cirlcled small black spot.
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `ActivityFinal`;
CREATE TABLE `ActivityFinal` # entityType=ActivityFinal tableId={445AA747-5297-440d-B5AB-7D03A8FED16E}
(
  `id` INT(11) NOT NULL, # columnId=_igwLx63YEd6pn5gd7VEuBA 
  `fk_package_id` INT(11), # columnId=_igwLwq3YEd6pn5gd7VEuBA referencedTable=Package
  `fk_activity_id` INT(11), # columnId=_igmaxa3YEd6pn5gd7VEuBA referencedTable=Activity
  `fk_activityset_id` INT(11), # columnId=_igmawK3YEd6pn5gd7VEuBA referencedTable=ActivitySet
  `alias` VARCHAR(255), # columnId=_igJu0K3YEd6pn5gd7VEuBA 
  `status` VARCHAR(255), # columnId=_igJu163YEd6pn5gd7VEuBA 
  `author` VARCHAR(255), # columnId=_igJu3a3YEd6pn5gd7VEuBA 
  `version` VARCHAR(255), # columnId=_igJu463YEd6pn5gd7VEuBA 
  `name` VARCHAR(255), # columnId=_igTf0K3YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_igTf163YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_igTf3q3YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_igTf5a3YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_igTf7K3YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_igTf863YEd6pn5gd7VEuBA 
  `sortkey` INT(11),
  PRIMARY KEY (`id`)
  ,KEY `fk_package_id` (`fk_package_id`)
  ,KEY `fk_activity_id` (`fk_activity_id`)
  ,KEY `fk_activityset_id` (`fk_activityset_id`)
) TYPE=MyISAM;
#
# Structure of Table `ChiSystem`
# a ChiSystem is a entity for the configuration of a specific technology. it is transformed in a section within a configuration file.
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `ChiSystem`;
CREATE TABLE `ChiSystem` # entityType=ChiSystem tableId={4C688225-1C73-42b8-80FF-A1D8FB1F660B}
(
  `id` INT(11) NOT NULL, # columnId=_iftC5a3YEd6pn5gd7VEuBA 
  `fk_package_id` INT(11), # columnId=_iftC4K3YEd6pn5gd7VEuBA referencedTable=Package
  `config` VARCHAR(255), # columnId={DB38A933-DA77-4b11-A4C8-3BD52C58D48A} 
  `plattform` VARCHAR(255), # columnId={1192FA16-2867-4021-A8AB-64B2B4FB2D97} 
  `alias` VARCHAR(255), # columnId=_ifQW8K3YEd6pn5gd7VEuBA 
  `status` VARCHAR(255), # columnId=_ifQW963YEd6pn5gd7VEuBA 
  `author` VARCHAR(255), # columnId=_ifQW_a3YEd6pn5gd7VEuBA 
  `version` VARCHAR(255), # columnId=_ifQXA63YEd6pn5gd7VEuBA 
  `name` VARCHAR(255), # columnId=_ifQXCq3YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_ifQXEa3YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_ifaH9a3YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_ifaH_K3YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_ifaIA63YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_ifaICq3YEd6pn5gd7VEuBA 
  `sortkey` INT(11),
  PRIMARY KEY (`id`)
  ,KEY `fk_package_id` (`fk_package_id`)
) TYPE=MyISAM;
#
# Structure of Table `Translation`
# Instances of this class are used to localize entity attributes. Each instance defines a translation of one attribute of one entity into one language.
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `Translation`;
CREATE TABLE `Translation` # entityType=Translation tableId={09F69DF1-0E20-4135-855A-3179FD436B8F}
(
  `id` INT(11) NOT NULL, # columnId=_i-2dAK3YEd6pn5gd7VEuBA 
  `objectid` VARCHAR(255), # columnId={822CEADC-526A-4347-A050-1F4F74148D88} 
  `attribute` VARCHAR(255), # columnId={65FC01D8-85D4-47c8-B2B1-CE0445408A3A} 
  `translation` TEXT, # columnId={C91D5D0C-5188-4bcb-8B44-53FA82ECE470} 
  `language` VARCHAR(255), # columnId={710A1A8E-F609-4cb3-95DE-76FA5A8D0A25} 
  PRIMARY KEY (`id`)
) TYPE=MyISAM;
#
# Structure of Table `adodbseq`
# 
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `adodbseq`;
CREATE TABLE `adodbseq` # entityType=Adodbseq tableId={3C3FC8F0-DD8A-4ad9-BB10-403825A48C9C}
(
  `id` INT(11) NOT NULL, # columnId=_i-QAEK3YEd6pn5gd7VEuBA 
  PRIMARY KEY (`id`)
) TYPE=MyISAM;
#
# Structure of Table `locktable`
# 
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `locktable`;
CREATE TABLE `locktable` # entityType=Locktable tableId={ADC6F227-2E89-41a1-8EA3-9B73820EC9D8}
(
  `id` INT(11) NOT NULL, # columnId=_i9qKNa3YEd6pn5gd7VEuBA 
  `fk_user_id` INT(11), # columnId=_i9qKMK3YEd6pn5gd7VEuBA referencedTable=UserRDB
  `objectid` VARCHAR(255), # columnId={C18AF095-575E-4c60-9240-37EE7976CEB5} 
  `sessionid` VARCHAR(255), # columnId={C690480B-E434-4675-807B-7DA3C1FC71E9} 
  `since` VARCHAR(255), # columnId={436EB7C1-122C-42c2-81F2-D519B950E934} 
  PRIMARY KEY (`id`)
  ,KEY `fk_user_id` (`fk_user_id`)
) TYPE=MyISAM;
#
# Structure of Table `nm_user_role`
# 
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `nm_user_role`;
CREATE TABLE `nm_user_role` # entityType=NMUserRole tableId={4AB7C88E-CE09-4fba-A8C9-1DBEEC9B5EFC}
(
  `fk_user_id` INT(11), # columnId=_i8wyVa3YEd6pn5gd7VEuBA referencedTable=UserRDB
  `fk_role_id` INT(11), # columnId=_i8wyUK3YEd6pn5gd7VEuBA referencedTable=RoleRDB
  PRIMARY KEY (`fk_user_id`,`fk_role_id`)
) TYPE=MyISAM;
#
# Structure of Table `role`
# 
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `role`;
CREATE TABLE `role` # entityType=RoleRDB tableId={74CB3FF5-27C7-435e-BECA-F3511F6A181D}
(
  `id` INT(11) NOT NULL, # columnId=_jEhAIK3YEd6pn5gd7VEuBA 
  `name` VARCHAR(50), # columnId={451E3B0C-4DF2-4f43-9F9E-88306EFE8D68} 
  PRIMARY KEY (`id`)
) TYPE=MyISAM;
#
# Structure of Table `user`
# 
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` # entityType=UserRDB tableId={B8AEA9E2-2228-42b9-9121-FDA1DF50E05D}
(
  `id` INT(11) NOT NULL, # columnId=_jBPCoK3YEd6pn5gd7VEuBA 
  `login` VARCHAR(50), # columnId={6FFE27BD-3B95-4828-B26A-A41AEC65B651} 
  `password` VARCHAR(255), # columnId={0F69EA9D-4963-4608-99DB-F35CE1159BDB} 
  `name` VARCHAR(50), # columnId={23BEDAEE-0278-4fb6-ABD1-E12AEE461A12} 
  `firstname` VARCHAR(50), # columnId={7AA15204-4902-45a5-AF96-599B511B4812} 
  `config` VARCHAR(255), # columnId={F0758E3B-E9D4-4dd9-A108-472A2CBE8CDA} 
  PRIMARY KEY (`id`)
) TYPE=MyISAM;
#
# Structure of Table `NMChiUseCaseChiUseCase`
# 
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `NMChiUseCaseChiUseCase`;
CREATE TABLE `NMChiUseCaseChiUseCase` # entityType=NMChiUseCaseChiUseCase tableId={5B939A0F-3C9C-48c9-954B-440615C258AC}
(
  `id` INT(11) NOT NULL, # columnId=_iw_nMK3YEd6pn5gd7VEuBA 
  `fk_chiusecasecoresource_id` INT(11), # columnId=_iw12P63YEd6pn5gd7VEuBA referencedTable=ChiBusinessUseCaseCore
  `fk_chiusecasecoretarget_id` INT(11), # columnId=_iw12Oq3YEd6pn5gd7VEuBA referencedTable=ChiBusinessUseCaseCore
  `fk_chiusecasetarget_id` INT(11), # columnId=_iw12Na3YEd6pn5gd7VEuBA referencedTable=ChiBusinessUseCase
  `fk_chiusecasesource_id` INT(11), # columnId=_iw12MK3YEd6pn5gd7VEuBA referencedTable=ChiBusinessUseCase
  `sourcemultiplicity` VARCHAR(255), # columnId=_iwQAUK3YEd6pn5gd7VEuBA 
  `sourcenavigability` VARCHAR(255), # columnId=_iwQAVq3YEd6pn5gd7VEuBA 
  `targetmultiplicity` VARCHAR(255), # columnId=_iwZKRK3YEd6pn5gd7VEuBA 
  `targetnavigability` VARCHAR(255), # columnId=_iwZKSq3YEd6pn5gd7VEuBA 
  `relationtype` VARCHAR(255), # columnId=_iwZKUK3YEd6pn5gd7VEuBA 
  `name` VARCHAR(255), # columnId=_iwZKV63YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_iwZKXq3YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_iwi7Ra3YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_iwi7TK3YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_iwi7U63YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_iwi7Wq3YEd6pn5gd7VEuBA 
  PRIMARY KEY (`id`)
  ,KEY `fk_chiusecasecoresource_id` (`fk_chiusecasecoresource_id`)
  ,KEY `fk_chiusecasecoretarget_id` (`fk_chiusecasecoretarget_id`)
  ,KEY `fk_chiusecasetarget_id` (`fk_chiusecasetarget_id`)
  ,KEY `fk_chiusecasesource_id` (`fk_chiusecasesource_id`)
) TYPE=MyISAM;
#
# Structure of Table `Actor`
# this class reppresent a generic actor.
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `Actor`;
CREATE TABLE `Actor` # entityType=Actor tableId={1134220A-E3FE-4daf-BC34-1DBA7BBB7DB2}
(
  `id` INT(11) NOT NULL, # columnId=_iZJu9a3YEd6pn5gd7VEuBA 
  `fk_package_id` INT(11), # columnId=_iZJu8K3YEd6pn5gd7VEuBA referencedTable=Package
  `alias` VARCHAR(255), # columnId=_iYtDAK3YEd6pn5gd7VEuBA 
  `status` VARCHAR(255), # columnId=_iYtDB63YEd6pn5gd7VEuBA 
  `author` VARCHAR(255), # columnId=_iYtDDa3YEd6pn5gd7VEuBA 
  `version` VARCHAR(255), # columnId=_iYtDE63YEd6pn5gd7VEuBA 
  `name` VARCHAR(255), # columnId=_iYtDGq3YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_iY20Bq3YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_iY20Da3YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_iY20FK3YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_iY20G63YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_iY20Iq3YEd6pn5gd7VEuBA 
  `sortkey` INT(11),
  PRIMARY KEY (`id`)
  ,KEY `fk_package_id` (`fk_package_id`)
) TYPE=MyISAM;
#
# Structure of Table `ChiWorker`
# A ChiWorker is a special actor that works within the enterprise. 
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `ChiWorker`;
CREATE TABLE `ChiWorker` # entityType=ChiWorker tableId={43750BBC-629B-4e5c-8ACB-1FD05AA35E62}
(
  `id` INT(11) NOT NULL, # columnId=_ic3xVa3YEd6pn5gd7VEuBA 
  `fk_package_id` INT(11), # columnId=_ic3xUK3YEd6pn5gd7VEuBA referencedTable=Package
  `alias` VARCHAR(255), # columnId=_icbscK3YEd6pn5gd7VEuBA 
  `status` VARCHAR(255), # columnId=_icbsd63YEd6pn5gd7VEuBA 
  `author` VARCHAR(255), # columnId=_icbsfa3YEd6pn5gd7VEuBA 
  `version` VARCHAR(255), # columnId=_icbsg63YEd6pn5gd7VEuBA 
  `name` VARCHAR(255), # columnId=_icbsiq3YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_icbska3YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_ick2Zq3YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_ick2ba3YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_ick2dK3YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_ick2e63YEd6pn5gd7VEuBA 
  `sortkey` INT(11),
  PRIMARY KEY (`id`)
  ,KEY `fk_package_id` (`fk_package_id`)
) TYPE=MyISAM;
#
# Structure of Table `ChiBusinessPartner`
# A ChiBusinesPartner is an external person that has a Business relation with the enterprise.
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `ChiBusinessPartner`;
CREATE TABLE `ChiBusinessPartner` # entityType=ChiBusinessPartner tableId={0518754B-9320-4acd-8B6D-869425C63F2A}
(
  `id` INT(11) NOT NULL, # columnId=_iaDG1a3YEd6pn5gd7VEuBA 
  `fk_package_id` INT(11), # columnId=_iaDG0K3YEd6pn5gd7VEuBA referencedTable=Package
  `alias` VARCHAR(255), # columnId=_iZma4K3YEd6pn5gd7VEuBA 
  `status` VARCHAR(255), # columnId=_iZma563YEd6pn5gd7VEuBA 
  `author` VARCHAR(255), # columnId=_iZma7a3YEd6pn5gd7VEuBA 
  `version` VARCHAR(255), # columnId=_iZma863YEd6pn5gd7VEuBA 
  `name` VARCHAR(255), # columnId=_iZma-q3YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_iZvk1q3YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_iZvk3a3YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_iZvk5K3YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_iZvk663YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_iZvk8q3YEd6pn5gd7VEuBA 
  `sortkey` INT(11),
  PRIMARY KEY (`id`)
  ,KEY `fk_package_id` (`fk_package_id`)
) TYPE=MyISAM;
#
# Structure of Table `ChiBusinessProcess`
# A Business Process is a sum of actions that produces a business advantage to the enterprise. It is composed by one or many ChiBusinessUseCases.
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `ChiBusinessProcess`;
CREATE TABLE `ChiBusinessProcess` # entityType=ChiBusinessProcess tableId={CF3A013D-F615-45c5-BE80-2604A693AAD3}
(
  `id` INT(11) NOT NULL, # columnId=_iYaIEK3YEd6pn5gd7VEuBA 
  `fk_package_id` INT(11), # columnId=_iYQXEK3YEd6pn5gd7VEuBA referencedTable=Package
  `alias` VARCHAR(255), # columnId=_iXzrIK3YEd6pn5gd7VEuBA 
  `status` VARCHAR(255), # columnId=_iXzrJ63YEd6pn5gd7VEuBA 
  `author` VARCHAR(255), # columnId=_iXzrLa3YEd6pn5gd7VEuBA 
  `version` VARCHAR(255), # columnId=_iXzrM63YEd6pn5gd7VEuBA 
  `name` VARCHAR(255), # columnId=_iXzrOq3YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_iX9cJq3YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_iX9cLa3YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_iX9cNK3YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_iX9cO63YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_iX9cQq3YEd6pn5gd7VEuBA 
  `sortkey` INT(11),
  PRIMARY KEY (`id`)
  ,KEY `fk_package_id` (`fk_package_id`)
) TYPE=MyISAM;
#
# Structure of Table `ChiBusinessUseCase`
# A Business Use Case is part of a business process that produces an advantage to the enterprise.
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `ChiBusinessUseCase`;
CREATE TABLE `ChiBusinessUseCase` # entityType=ChiBusinessUseCase tableId={A59A19CD-77D2-4018-9BB1-768011088E88}
(
  `id` INT(11) NOT NULL, # columnId=_iV3xf63YEd6pn5gd7VEuBA 
  `fk_package_id` INT(11), # columnId=_iV3xeq3YEd6pn5gd7VEuBA referencedTable=Package
  `fk_chifeature_id` INT(11), # columnId=_iV3xda3YEd6pn5gd7VEuBA referencedTable=ChiFeature
  `fk_chibusinessprocess_id` INT(11), # columnId=_iV3xcK3YEd6pn5gd7VEuBA referencedTable=ChiBusinessProcess
  `primaryactor` VARCHAR(255), # columnId={4041F610-32BC-4189-B2DC-A39C60D94F05} 
  `otheractors` VARCHAR(255), # columnId={81EC46D8-DF2B-4ab2-B858-561EAFD144C4} 
  `goalincontext` VARCHAR(255), # columnId={D8CF4340-B3F6-4a7d-8B89-1ED7CD5A8A3B} 
  `scope` VARCHAR(255), # columnId={457D6B8F-5C6C-4614-A4AE-B7219A490CB6} 
  `level` VARCHAR(255), # columnId={473B21EA-AE12-483b-8742-31DC9775A8DE} 
  `stakeholders` VARCHAR(255), # columnId={FD8341F1-A37A-4e05-995B-C8DF570F5DE9} 
  `precondition` VARCHAR(255), # columnId={F965589A-94D9-4589-B79A-01000B433301} 
  `trigger` VARCHAR(255), # columnId={544C139A-724F-4d10-8F4E-0C0BB70957BC} 
  `mainsuccessscenario` VARCHAR(255), # columnId={6B11E95D-EB71-4741-A81D-52F8CE4343F1} 
  `extensions` VARCHAR(255), # columnId={A50BA5A6-35A0-46ea-ADE4-A0A65E31FA3A} 
  `alias` VARCHAR(255), # columnId=_iVR7kK3YEd6pn5gd7VEuBA 
  `status` VARCHAR(255), # columnId=_iVR7l63YEd6pn5gd7VEuBA 
  `author` VARCHAR(255), # columnId=_iVR7na3YEd6pn5gd7VEuBA 
  `version` VARCHAR(255), # columnId=_iVbFha3YEd6pn5gd7VEuBA 
  `name` VARCHAR(255), # columnId=_iVbFjK3YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_iVbFk63YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_iVbFmq3YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_iVbFoa3YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_iVbFqK3YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_iVk2gK3YEd6pn5gd7VEuBA 
  `sortkey` INT(11),
  PRIMARY KEY (`id`)
  ,KEY `fk_package_id` (`fk_package_id`)
  ,KEY `fk_chifeature_id` (`fk_chifeature_id`)
  ,KEY `fk_chibusinessprocess_id` (`fk_chibusinessprocess_id`)
) TYPE=MyISAM;
#
# Structure of Table `ChiBusinessUseCaseCore`
# A Core Use Case generates a value for an active business partner and is directly connected to the objectives (ChiGoals) of a company or the process of his existence (typically making money).
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `ChiBusinessUseCaseCore`;
CREATE TABLE `ChiBusinessUseCaseCore` # entityType=ChiBusinessUseCaseCore tableId={63789429-77BC-46a1-81D8-1D06696D0669}
(
  `id` INT(11) NOT NULL, # columnId=_iXgwNa3YEd6pn5gd7VEuBA 
  `fk_chibusinessprocess_id` INT(11), # columnId=_iXgwMK3YEd6pn5gd7VEuBA referencedTable=ChiBusinessProcess
  `fk_chifeature_id` INT(11), # columnId=_iXW_Na3YEd6pn5gd7VEuBA referencedTable=ChiFeature
  `fk_package_id` INT(11), # columnId=_iXW_MK3YEd6pn5gd7VEuBA referencedTable=Package
  `primaryactor` VARCHAR(255), # columnId=_iWnYWq3YEd6pn5gd7VEuBA 
  `otheractors` VARCHAR(255), # columnId=_iWnYYa3YEd6pn5gd7VEuBA 
  `goalincontext` VARCHAR(255), # columnId=_iWnYaK3YEd6pn5gd7VEuBA 
  `scope` VARCHAR(255), # columnId=_iWnYb63YEd6pn5gd7VEuBA 
  `level` VARCHAR(255), # columnId=_iWxJVq3YEd6pn5gd7VEuBA 
  `stakeholders` VARCHAR(255), # columnId=_iWxJXa3YEd6pn5gd7VEuBA 
  `precondition` VARCHAR(255), # columnId=_iWxJZK3YEd6pn5gd7VEuBA 
  `trigger` VARCHAR(255), # columnId=_iWxJa63YEd6pn5gd7VEuBA 
  `mainsuccessscenario` VARCHAR(255), # columnId=_iWxJcq3YEd6pn5gd7VEuBA 
  `extensions` VARCHAR(255), # columnId=_iWxJea3YEd6pn5gd7VEuBA 
  `alias` VARCHAR(255), # columnId=_iW6TRK3YEd6pn5gd7VEuBA 
  `status` VARCHAR(255), # columnId=_iW6TS63YEd6pn5gd7VEuBA 
  `author` VARCHAR(255), # columnId=_iW6TUa3YEd6pn5gd7VEuBA 
  `version` VARCHAR(255), # columnId=_iW6TV63YEd6pn5gd7VEuBA 
  `name` VARCHAR(255), # columnId=_iW6TXq3YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_iW6TZa3YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_iXEERa3YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_iXEETK3YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_iXEEU63YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_iXEEWq3YEd6pn5gd7VEuBA 
  `sortkey` INT(11),
  PRIMARY KEY (`id`)
  ,KEY `fk_chibusinessprocess_id` (`fk_chibusinessprocess_id`)
  ,KEY `fk_chifeature_id` (`fk_chifeature_id`)
  ,KEY `fk_package_id` (`fk_package_id`)
) TYPE=MyISAM;
#
# Structure of Table `ChiBusinessPartnerActive`
# A ChiBusinesPartnerActive is a direct customer of the enterprise.
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `ChiBusinessPartnerActive`;
CREATE TABLE `ChiBusinessPartnerActive` # entityType=ChiBusinessPartnerActive tableId={A7C01B9A-19CF-43e8-AD85-7FD7DB295110}
(
  `id` INT(11) NOT NULL, # columnId=_ib_Aiq3YEd6pn5gd7VEuBA 
  `fk_package_id` INT(11), # columnId=_ib_Aha3YEd6pn5gd7VEuBA referencedTable=Package
  `fk_chibusinesspartneractive_id` INT(11), # columnId=_ib_AgK3YEd6pn5gd7VEuBA referencedTable=ChiBusinessPartnerActive
  `alias` VARCHAR(255), # columnId=_ibYjmq3YEd6pn5gd7VEuBA 
  `status` VARCHAR(255), # columnId=_ibiUlq3YEd6pn5gd7VEuBA 
  `author` VARCHAR(255), # columnId=_ibiUnK3YEd6pn5gd7VEuBA 
  `version` VARCHAR(255), # columnId=_ibiUoq3YEd6pn5gd7VEuBA 
  `name` VARCHAR(255), # columnId=_ibiUqa3YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_ibiUsK3YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_ibreha3YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_ibrejK3YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_ibrek63YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_ibremq3YEd6pn5gd7VEuBA 
  `sortkey` INT(11),
  PRIMARY KEY (`id`)
  ,KEY `fk_package_id` (`fk_package_id`)
  ,KEY `fk_chibusinesspartneractive_id` (`fk_chibusinesspartneractive_id`)
) TYPE=MyISAM;
#
# Structure of Table `ChiBusinessPartnerPassive`
# A ChiBusinesPartnerPassive is an indirect customer (typically a supplier) of the enterprise.
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `ChiBusinessPartnerPassive`;
CREATE TABLE `ChiBusinessPartnerPassive` # entityType=ChiBusinessPartnerPassive tableId={E82AFF41-CB05-4829-AA2A-402A1EAB7292}
(
  `id` INT(11) NOT NULL, # columnId=_ibFopa3YEd6pn5gd7VEuBA 
  `fk_package_id` INT(11), # columnId=_ibFooK3YEd6pn5gd7VEuBA referencedTable=Package
  `fk_chibusinesspartnerpassive_id` INT(11), # columnId=_ia73oK3YEd6pn5gd7VEuBA referencedTable=ChiBusinessPartnerPassive
  `alias` VARCHAR(255), # columnId=_iafLuq3YEd6pn5gd7VEuBA 
  `status` VARCHAR(255), # columnId=_iafLwa3YEd6pn5gd7VEuBA 
  `author` VARCHAR(255), # columnId=_iafLx63YEd6pn5gd7VEuBA 
  `version` VARCHAR(255), # columnId=_iafLza3YEd6pn5gd7VEuBA 
  `name` VARCHAR(255), # columnId=_iao8tq3YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_iao8va3YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_iao8xK3YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_iao8y63YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_iao80q3YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_iao82a3YEd6pn5gd7VEuBA 
  `sortkey` INT(11),
  PRIMARY KEY (`id`)
  ,KEY `fk_package_id` (`fk_package_id`)
  ,KEY `fk_chibusinesspartnerpassive_id` (`fk_chibusinesspartnerpassive_id`)
) TYPE=MyISAM;
#
# Structure of Table `ChiWorkerExternal`
# A Chi External Worker is an employee that interacts directly with ChiBusinesPartner outside the enterprise.
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `ChiWorkerExternal`;
CREATE TABLE `ChiWorkerExternal` # entityType=ChiWorkerExternal tableId={52B75F68-6CC4-42bc-875F-E778C772B4C6}
(
  `id` INT(11) NOT NULL, # columnId=_ie0SGq3YEd6pn5gd7VEuBA 
  `fk_package_id` INT(11), # columnId=_ie0SFa3YEd6pn5gd7VEuBA referencedTable=Package
  `fk_chiworkerexternal_id` INT(11), # columnId=_ie0SEK3YEd6pn5gd7VEuBA referencedTable=ChiWorkerExternal
  `is_offlineuser` VARCHAR(255), # columnId={A86A8961-C0FE-49a5-8932-186FB6992842} 
  `alias` VARCHAR(255), # columnId=_ieN1Kq3YEd6pn5gd7VEuBA 
  `status` VARCHAR(255), # columnId=_ieN1Ma3YEd6pn5gd7VEuBA 
  `author` VARCHAR(255), # columnId=_ieXmJK3YEd6pn5gd7VEuBA 
  `version` VARCHAR(255), # columnId=_ieXmKq3YEd6pn5gd7VEuBA 
  `name` VARCHAR(255), # columnId=_ieXmMa3YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_ieXmOK3YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_ieXmP63YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_ieXmRq3YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_iegwFq3YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_iegwHa3YEd6pn5gd7VEuBA 
  `sortkey` INT(11),
  PRIMARY KEY (`id`)
  ,KEY `fk_package_id` (`fk_package_id`)
  ,KEY `fk_chiworkerexternal_id` (`fk_chiworkerexternal_id`)
) TYPE=MyISAM;
#
# Structure of Table `ChiWorkerInternal`
# A Chi  Worker Internal is an employee of the enterprise that has no contact with Business partners.
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `ChiWorkerInternal`;
CREATE TABLE `ChiWorkerInternal` # entityType=ChiWorkerInternal tableId={2A793A11-60C7-4108-9C85-18F6F015505F}
(
  `id` INT(11) NOT NULL, # columnId=_id66Na3YEd6pn5gd7VEuBA 
  `fk_package_id` INT(11), # columnId=_id66MK3YEd6pn5gd7VEuBA referencedTable=Package
  `fk_chiworkerinternal_id` INT(11), # columnId=_idxJMK3YEd6pn5gd7VEuBA referencedTable=ChiWorkerInternal
  `alias` VARCHAR(255), # columnId=_idUdSq3YEd6pn5gd7VEuBA 
  `status` VARCHAR(255), # columnId=_idUdUa3YEd6pn5gd7VEuBA 
  `author` VARCHAR(255), # columnId=_idUdV63YEd6pn5gd7VEuBA 
  `version` VARCHAR(255), # columnId=_idUdXa3YEd6pn5gd7VEuBA 
  `name` VARCHAR(255), # columnId=_ideORq3YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_ideOTa3YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_ideOVK3YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_ideOW63YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_ideOYq3YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_ideOaa3YEd6pn5gd7VEuBA 
  `sortkey` INT(11),
  PRIMARY KEY (`id`)
  ,KEY `fk_package_id` (`fk_package_id`)
  ,KEY `fk_chiworkerinternal_id` (`fk_chiworkerinternal_id`)
) TYPE=MyISAM;
#
# Structure of Table `NMUCActor`
# 
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `NMUCActor`;
CREATE TABLE `NMUCActor` # entityType=NMUCActor tableId={0863D9E9-ADE5-4c27-9118-97B5FEECAEAE}
(
  `id` INT(11) NOT NULL, # columnId=_i8BLf63YEd6pn5gd7VEuBA 
  `fk_chiworkerexternal_id` INT(11), # columnId=_i8BLeq3YEd6pn5gd7VEuBA referencedTable=ChiWorkerExternal
  `fk_chiworkerinternal_id` INT(11), # columnId=_i8BLda3YEd6pn5gd7VEuBA referencedTable=ChiWorkerInternal
  `fk_chiworker_id` INT(11), # columnId=_i8BLcK3YEd6pn5gd7VEuBA referencedTable=ChiWorker
  `fk_chibusinesspartneractive_id` INT(11), # columnId=_i73aia3YEd6pn5gd7VEuBA referencedTable=ChiBusinessPartnerActive
  `fk_chibusinesspartnerpassive_id` INT(11), # columnId=_i73ahK3YEd6pn5gd7VEuBA referencedTable=ChiBusinessPartnerPassive
  `fk_chibusinesspartner_id` INT(11), # columnId=_i73af63YEd6pn5gd7VEuBA referencedTable=ChiBusinessPartner
  `fk_chibusinessusecasecore_id` INT(11), # columnId=_i73aeq3YEd6pn5gd7VEuBA referencedTable=ChiBusinessUseCaseCore
  `fk_chibusinessusecase_id` INT(11), # columnId=_i73ada3YEd6pn5gd7VEuBA referencedTable=ChiBusinessUseCase
  `fk_actor_id` INT(11), # columnId=_i73acK3YEd6pn5gd7VEuBA referencedTable=Actor
  PRIMARY KEY (`id`)
  ,KEY `fk_chiworkerexternal_id` (`fk_chiworkerexternal_id`)
  ,KEY `fk_chiworkerinternal_id` (`fk_chiworkerinternal_id`)
  ,KEY `fk_chiworker_id` (`fk_chiworker_id`)
  ,KEY `fk_chibusinesspartneractive_id` (`fk_chibusinesspartneractive_id`)
  ,KEY `fk_chibusinesspartnerpassive_id` (`fk_chibusinesspartnerpassive_id`)
  ,KEY `fk_chibusinesspartner_id` (`fk_chibusinesspartner_id`)
  ,KEY `fk_chibusinessusecasecore_id` (`fk_chibusinessusecasecore_id`)
  ,KEY `fk_chibusinessusecase_id` (`fk_chibusinessusecase_id`)
  ,KEY `fk_actor_id` (`fk_actor_id`)
) TYPE=MyISAM;
#
# Structure of Table `ChiGoal`
# a Measurable scope that the enterprise wants to achieve. 
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `ChiGoal`;
CREATE TABLE `ChiGoal` # entityType=ChiGoal tableId={C78BC7DD-DA11-463c-A937-F5BFA7660EAB}
(
  `id` INT(11) NOT NULL, # columnId=_iU-Zla3YEd6pn5gd7VEuBA 
  `fk_package_id` INT(11), # columnId=_iU-ZkK3YEd6pn5gd7VEuBA referencedTable=Package
  `fk_chigoal_id` INT(11), # columnId=_iU1PoK3YEd6pn5gd7VEuBA referencedTable=ChiGoal
  `priority` VARCHAR(255), # columnId={F6E9EAC8-F4CA-4fe5-B343-23FE55DC6B6A} 
  `value_ammount` VARCHAR(255), # columnId={D5E47AFF-F63E-4e8a-98F4-D854F99A8607} 
  `value_goal` VARCHAR(255), # columnId={4A005AF8-CC83-4169-9D5D-6A71A85F90A0} 
  `value_name` VARCHAR(255), # columnId={5C83F67E-8051-4cde-AB4D-0C9EDE940D7E} 
  `goaltype` VARCHAR(255), # columnId={7221AB7B-84CE-4716-A1F7-CF25CEB5D241} 
  `alias` VARCHAR(255), # columnId=_iSS5AK3YEd6pn5gd7VEuBA 
  `status` VARCHAR(255), # columnId=_iSS5B63YEd6pn5gd7VEuBA 
  `author` VARCHAR(255), # columnId=_iScqBK3YEd6pn5gd7VEuBA 
  `version` VARCHAR(255), # columnId=_iUhtoK3YEd6pn5gd7VEuBA 
  `name` VARCHAR(255), # columnId=_iUhtp63YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_iUhtrq3YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_iUhtta3YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_iUhtvK3YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_iUhtw63YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_iUhtyq3YEd6pn5gd7VEuBA 
  `sortkey` INT(11),
  PRIMARY KEY (`id`)
  ,KEY `fk_package_id` (`fk_package_id`)
  ,KEY `fk_chigoal_id` (`fk_chigoal_id`)
) TYPE=MyISAM;
#
# Structure of Table `ChiRequirement`
# A Business guide line about the Enterprise or the project.
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `ChiRequirement`;
CREATE TABLE `ChiRequirement` # entityType=ChiRequirement tableId={1169EE51-B124-402a-8430-12D6680C48DD}
(
  `id` INT(11) NOT NULL, # columnId=_iR_-H63YEd6pn5gd7VEuBA 
  `fk_package_id` INT(11), # columnId=_iR_-Gq3YEd6pn5gd7VEuBA referencedTable=Package
  `fk_chirequirement_id` INT(11), # columnId=_iR_-Fa3YEd6pn5gd7VEuBA referencedTable=ChiRequirement
  `fk_chigoal_id` INT(11), # columnId=_iR_-EK3YEd6pn5gd7VEuBA referencedTable=ChiGoal
  `reqtype` VARCHAR(255), # columnId={6BE90587-3033-4d4c-9D05-20FCC7B5D2D1} 
  `priority` VARCHAR(255), # columnId={E5696387-DC21-47a7-B0E0-B99AF858D519} 
  `author` VARCHAR(255), # columnId={FD9FE2DB-EC74-4362-83DC-2DDD333A4279} 
  `proofreader` VARCHAR(255), # columnId={BB67DFA4-93B5-4212-AFE0-D59FF31FD90A} 
  `status` VARCHAR(255), # columnId={87D413FB-7BD7-4ce1-A394-5AC92102484B} 
  `alias` VARCHAR(255), # columnId=_iRZhIK3YEd6pn5gd7VEuBA 
  `version` VARCHAR(255), # columnId=_iRjSJa3YEd6pn5gd7VEuBA 
  `name` VARCHAR(255), # columnId=_iRjSLK3YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_iRjSM63YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_iRjSOq3YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_iRjSQa3YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_iRjSSK3YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_iRtDJq3YEd6pn5gd7VEuBA 
  `sortkey` INT(11),
  PRIMARY KEY (`id`)
  ,KEY `fk_package_id` (`fk_package_id`)
  ,KEY `fk_chirequirement_id` (`fk_chirequirement_id`)
  ,KEY `fk_chigoal_id` (`fk_chigoal_id`)
) TYPE=MyISAM;
#
# Structure of Table `ChiFeature`
# 
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `ChiFeature`;
CREATE TABLE `ChiFeature` # entityType=ChiFeature tableId={81FDBF74-10F8-403a-A886-BA51DFFA2263}
(
  `id` INT(11) NOT NULL, # columnId=_iRGmNa3YEd6pn5gd7VEuBA 
  `fk_package_id` INT(11), # columnId=_iRGmMK3YEd6pn5gd7VEuBA referencedTable=Package
  `author` VARCHAR(255), # columnId={B8B932B0-4DB5-4b2f-B5DC-77539B897D78} 
  `proofreader` VARCHAR(255), # columnId={DCB9B590-FB72-4745-8ED3-C194543F17E8} 
  `status` VARCHAR(255), # columnId={8DF13718-C83D-4a82-9492-E8E243EE8376} 
  `alias` VARCHAR(255), # columnId=_iQp6QK3YEd6pn5gd7VEuBA 
  `version` VARCHAR(255), # columnId=_iQp6R63YEd6pn5gd7VEuBA 
  `name` VARCHAR(255), # columnId=_iQp6Tq3YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_iQp6Va3YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_iQzrRa3YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_iQzrTK3YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_iQzrU63YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_iQzrWq3YEd6pn5gd7VEuBA 
  `sortkey` INT(11),
  PRIMARY KEY (`id`)
  ,KEY `fk_package_id` (`fk_package_id`)
) TYPE=MyISAM;
#
# Structure of Table `ChiIssue`
# 
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `ChiIssue`;
CREATE TABLE `ChiIssue` # entityType=ChiIssue tableId={E7461E91-24F7-4be8-9913-0E53305ED0E9}
(
  `id` INT(11) NOT NULL, # columnId=_iQEEaq3YEd6pn5gd7VEuBA 
  `fk_package_id` INT(11), # columnId=_iQEEZa3YEd6pn5gd7VEuBA referencedTable=Package
  `fk_chirequirement_id` INT(11), # columnId=_iQEEYK3YEd6pn5gd7VEuBA referencedTable=ChiRequirement
  `author` VARCHAR(255), # columnId={B0485347-2C52-4f90-BD0A-51636A4286F3} 
  `responsible` VARCHAR(255), # columnId={1EFDFCC4-23FA-4d6b-ABDC-FA778BEA128D} 
  `alias` VARCHAR(255), # columnId=_iPdncK3YEd6pn5gd7VEuBA 
  `status` VARCHAR(255), # columnId=_iPdnd63YEd6pn5gd7VEuBA 
  `version` VARCHAR(255), # columnId=_iPdnfa3YEd6pn5gd7VEuBA 
  `name` VARCHAR(255), # columnId=_iPnYcK3YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_iPnYd63YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_iPnYfq3YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_iPnYha3YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_iPnYjK3YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_iPnYk63YEd6pn5gd7VEuBA 
  `sortkey` INT(11),
  PRIMARY KEY (`id`)
  ,KEY `fk_package_id` (`fk_package_id`)
  ,KEY `fk_chirequirement_id` (`fk_chirequirement_id`)
) TYPE=MyISAM;
#
# Structure of Table `ChiFeatureStatus`
# 
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `ChiFeatureStatus`;
CREATE TABLE `ChiFeatureStatus` # entityType=ChiFeatureStatus tableId={4EFCA1BF-35BD-4395-A2E2-CE5ECC2DF98C}
(
  `id` INT(11) NOT NULL, # columnId=_i3ssIK3YEd6pn5gd7VEuBA 
  `name` VARCHAR(255), # columnId=_i3ZxMK3YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_i3ZxN63YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_i3i7Ja3YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_i3i7LK3YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_i3i7M63YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_i3i7Oq3YEd6pn5gd7VEuBA 
  PRIMARY KEY (`id`)
) TYPE=MyISAM;
#
# Structure of Table `ChiGoalType`
# the type of Goal (eg. Strategic, Operational, Vision, etc).
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `ChiGoalType`;
CREATE TABLE `ChiGoalType` # entityType=ChiGoalType tableId={099D0E49-5969-4f74-996D-173775CCBFD6}
(
  `id` INT(11) NOT NULL, # columnId=_i29FQK3YEd6pn5gd7VEuBA 
  `name` VARCHAR(255), # columnId=_i2gZUK3YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_i2qKVq3YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_i2qKXa3YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_i2qKZK3YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_i2qKa63YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_i2qKcq3YEd6pn5gd7VEuBA 
  PRIMARY KEY (`id`)
) TYPE=MyISAM;
#
# Structure of Table `ChiRequirementStatus`
# 
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `ChiRequirementStatus`;
CREATE TABLE `ChiRequirementStatus` # entityType=ChiRequirementStatus tableId={253B1C26-A49E-4b52-BEDD-2F470DC6FEDE}
(
  `id` INT(11) NOT NULL, # columnId=_i2DtYK3YEd6pn5gd7VEuBA 
  `name` VARCHAR(255), # columnId=_i158YK3YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_i158Z63YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_i158bq3YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_i158da3YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_i158fK3YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_i158g63YEd6pn5gd7VEuBA 
  PRIMARY KEY (`id`)
) TYPE=MyISAM;
#
# Structure of Table `ChiRequirementType`
# Type of requirement
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `ChiRequirementType`;
CREATE TABLE `ChiRequirementType` # entityType=ChiRequirementType tableId={B4D8CC31-7D39-46cd-A2B6-2D57DF2A04CF}
(
  `id` INT(11) NOT NULL, # columnId=_i1d3gK3YEd6pn5gd7VEuBA 
  `name` VARCHAR(255), # columnId=_i1KVgK3YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_i1KVh63YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_i1KVjq3YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_i1KVla3YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_i1KVnK3YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_i1KVo63YEd6pn5gd7VEuBA 
  PRIMARY KEY (`id`)
) TYPE=MyISAM;
#
# Structure of Table `NMFeatureRequirements`
# 
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `NMFeatureRequirements`;
CREATE TABLE `NMFeatureRequirements` # entityType=NMFeatureRequirements tableId={03F15877-01B7-4386-A6AA-D42EF3E2579D}
(
  `id` INT(11) NOT NULL, # columnId=_i604qq3YEd6pn5gd7VEuBA 
  `fk_chifeature_id` INT(11), # columnId=_i604pa3YEd6pn5gd7VEuBA referencedTable=ChiFeature
  `fk_chirequirement_id` INT(11), # columnId=_i604oK3YEd6pn5gd7VEuBA referencedTable=ChiRequirement
  PRIMARY KEY (`id`)
  ,KEY `fk_chifeature_id` (`fk_chifeature_id`)
  ,KEY `fk_chirequirement_id` (`fk_chirequirement_id`)
) TYPE=MyISAM;
#
# Structure of Table `ChiActionKey`
# An action key used in Chronos. An action key associates two controllers (to define a control flow) or a view with a controller (to define a view attachment). Controller, Views and Associations define the application flow.
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `ChiActionKey`;
CREATE TABLE `ChiActionKey` # entityType=ChiActionKey tableId={2C8F5231-26C9-4b35-AE10-C5A929FE3A59}
(
  `id` INT(11) NOT NULL, # columnId=_ittpsK3YEd6pn5gd7VEuBA 
  `action` VARCHAR(255), # columnId={F06E1949-72AB-4947-8971-6927F197AD69} 
  `config` VARCHAR(255), # columnId={34D5040C-0C5F-419c-B7CC-AD3CDF665343} 
  `context` VARCHAR(255), # columnId={FB3C1758-9A05-4404-9C71-E337A0E5B60C} 
  `sourcemultiplicity` VARCHAR(255), # columnId=_itQ9wK3YEd6pn5gd7VEuBA 
  `sourcenavigability` VARCHAR(255), # columnId=_itQ9xq3YEd6pn5gd7VEuBA 
  `targetmultiplicity` VARCHAR(255), # columnId=_itQ9zK3YEd6pn5gd7VEuBA 
  `targetnavigability` VARCHAR(255), # columnId=_itQ90q3YEd6pn5gd7VEuBA 
  `relationtype` VARCHAR(255), # columnId=_itQ92K3YEd6pn5gd7VEuBA 
  `name` VARCHAR(255), # columnId=_itauxq3YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_itauza3YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_itau1K3YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_itau263YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_itau4q3YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_itau6a3YEd6pn5gd7VEuBA 
  PRIMARY KEY (`id`)
) TYPE=MyISAM;
#
# Structure of Table `NMChiControllerActionKeyChiController`
# this class defines a control flow.
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `NMChiControllerActionKeyChiController`;
CREATE TABLE `NMChiControllerActionKeyChiController` # entityType=NMChiControllerActionKeyChiController tableId={00856565-97CA-4b29-8017-82135505535E}
(
  `id` INT(11) NOT NULL, # columnId=_ivzUaq3YEd6pn5gd7VEuBA 
  `fk_chicontrolleractionkeytarget_id` INT(11), # columnId=_ivzUZa3YEd6pn5gd7VEuBA referencedTable=ChiController
  `fk_chicontrolleractionkeysource_id` INT(11), # columnId=_ivzUYK3YEd6pn5gd7VEuBA referencedTable=ChiController
  `action` VARCHAR(255), # columnId=_ivM3cK3YEd6pn5gd7VEuBA 
  `config` VARCHAR(255), # columnId=_ivM3d63YEd6pn5gd7VEuBA 
  `context` VARCHAR(255), # columnId=_ivM3fq3YEd6pn5gd7VEuBA 
  `sourcemultiplicity` VARCHAR(255), # columnId=_ivM3ha3YEd6pn5gd7VEuBA 
  `sourcenavigability` VARCHAR(255), # columnId=_ivM3i63YEd6pn5gd7VEuBA 
  `targetmultiplicity` VARCHAR(255), # columnId=_ivM3ka3YEd6pn5gd7VEuBA 
  `targetnavigability` VARCHAR(255), # columnId=_ivWoda3YEd6pn5gd7VEuBA 
  `relationtype` VARCHAR(255), # columnId=_ivWoe63YEd6pn5gd7VEuBA 
  `name` VARCHAR(255), # columnId=_ivWogq3YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_ivWoia3YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_ivWokK3YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_ivgZdK3YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_ivgZe63YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_ivgZgq3YEd6pn5gd7VEuBA 
  PRIMARY KEY (`id`)
  ,KEY `fk_chicontrolleractionkeytarget_id` (`fk_chicontrolleractionkeytarget_id`)
  ,KEY `fk_chicontrolleractionkeysource_id` (`fk_chicontrolleractionkeysource_id`)
) TYPE=MyISAM;
#
# Structure of Table `NMChiControllerActionKeyChiView`
# 
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `NMChiControllerActionKeyChiView`;
CREATE TABLE `NMChiControllerActionKeyChiView` # entityType=NMChiControllerActionKeyChiView tableId={835030B8-ACFF-4ac2-9933-A41D3C8CF097}
(
  `id` INT(11) NOT NULL, # columnId=_iuwLiq3YEd6pn5gd7VEuBA 
  `fk_chiview_id` INT(11), # columnId=_iuwLha3YEd6pn5gd7VEuBA referencedTable=ChiView
  `fk_chicontroller_id` INT(11), # columnId=_iuwLgK3YEd6pn5gd7VEuBA referencedTable=ChiController
  `action` VARCHAR(255), # columnId=_iuAkoK3YEd6pn5gd7VEuBA 
  `config` VARCHAR(255), # columnId=_iuAkp63YEd6pn5gd7VEuBA 
  `context` VARCHAR(255), # columnId=_iuKVpq3YEd6pn5gd7VEuBA 
  `sourcemultiplicity` VARCHAR(255), # columnId=_iuKVra3YEd6pn5gd7VEuBA 
  `sourcenavigability` VARCHAR(255), # columnId=_iuKVs63YEd6pn5gd7VEuBA 
  `targetmultiplicity` VARCHAR(255), # columnId=_iuKVua3YEd6pn5gd7VEuBA 
  `targetnavigability` VARCHAR(255), # columnId=_iuKVv63YEd6pn5gd7VEuBA 
  `relationtype` VARCHAR(255), # columnId=_iuUGpK3YEd6pn5gd7VEuBA 
  `name` VARCHAR(255), # columnId=_iuUGq63YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_iuUGsq3YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_iuUGua3YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_iuUGwK3YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_iuUGx63YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_iudQlq3YEd6pn5gd7VEuBA 
  PRIMARY KEY (`id`)
  ,KEY `fk_chiview_id` (`fk_chiview_id`)
  ,KEY `fk_chicontroller_id` (`fk_chicontroller_id`)
) TYPE=MyISAM;
#
# Structure of Table `NMChiNodeChiMany2Many`
# 
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `NMChiNodeChiMany2Many`;
CREATE TABLE `NMChiNodeChiMany2Many` # entityType=NMChiNodeChiMany2Many tableId={482AB3B7-7B9D-4301-94B3-578CC9B7D603}
(
  `id` INT(11) NOT NULL, # columnId=_is0R2q3YEd6pn5gd7VEuBA 
  `fk_chinode_id` INT(11), # columnId=_is0R1a3YEd6pn5gd7VEuBA referencedTable=ChiNode
  `fk_chinodemanytomany_id` INT(11), # columnId=_is0R0K3YEd6pn5gd7VEuBA referencedTable=ChiNodeManyToMany
  `sourcemultiplicity` VARCHAR(255), # columnId=_isOb8K3YEd6pn5gd7VEuBA 
  `sourcenavigability` VARCHAR(255), # columnId=_isOb9q3YEd6pn5gd7VEuBA 
  `targetmultiplicity` VARCHAR(255), # columnId=_isOb_K3YEd6pn5gd7VEuBA 
  `targetnavigability` VARCHAR(255), # columnId=_isXl463YEd6pn5gd7VEuBA 
  `relationtype` VARCHAR(255), # columnId=_isXl6a3YEd6pn5gd7VEuBA 
  `name` VARCHAR(255), # columnId=_isXl8K3YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_isXl963YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_isXl_q3YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_isXmBa3YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_ishW5a3YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_ishW7K3YEd6pn5gd7VEuBA 
  PRIMARY KEY (`id`)
  ,KEY `fk_chinode_id` (`fk_chinode_id`)
  ,KEY `fk_chinodemanytomany_id` (`fk_chinodemanytomany_id`)
) TYPE=MyISAM;
#
# Structure of Table `NMChiControllerChiController`
# this class handle all the relationships between ChiControllers.
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `NMChiControllerChiController`;
CREATE TABLE `NMChiControllerChiController` # entityType=NMChiControllerChiController tableId={2B6FEDA4-F148-42dd-8F43-674F008DAE5C}
(
  `id` INT(11) NOT NULL, # columnId=_irxwCq3YEd6pn5gd7VEuBA 
  `fk_chicontrollertarget_id` INT(11), # columnId=_irxwBa3YEd6pn5gd7VEuBA referencedTable=ChiController
  `fk_chicontrollersource_id` INT(11), # columnId=_irxwAK3YEd6pn5gd7VEuBA referencedTable=ChiController
  `sourcemultiplicity` VARCHAR(255), # columnId=_irLTEK3YEd6pn5gd7VEuBA 
  `sourcenavigability` VARCHAR(255), # columnId=_irLTFq3YEd6pn5gd7VEuBA 
  `targetmultiplicity` VARCHAR(255), # columnId=_irVEFa3YEd6pn5gd7VEuBA 
  `targetnavigability` VARCHAR(255), # columnId=_irVEG63YEd6pn5gd7VEuBA 
  `relationtype` VARCHAR(255), # columnId=_irVEIa3YEd6pn5gd7VEuBA 
  `name` VARCHAR(255), # columnId=_irVEKK3YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_ire1Fa3YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_ire1HK3YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_ire1I63YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_ire1Kq3YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_ire1Ma3YEd6pn5gd7VEuBA 
  PRIMARY KEY (`id`)
  ,KEY `fk_chicontrollertarget_id` (`fk_chicontrollertarget_id`)
  ,KEY `fk_chicontrollersource_id` (`fk_chicontrollersource_id`)
) TYPE=MyISAM;
#
# Structure of Table `ChiClass`
# this object reppresent a UML::class
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `ChiClass`;
CREATE TABLE `ChiClass` # entityType=ChiClass tableId={D4660360-1AAB-4a88-97A3-0E1FA9C96E4B}
(
  `id` INT(11) NOT NULL, # columnId=_iKGmVa3YEd6pn5gd7VEuBA 
  `fk_package_id` INT(11), # columnId=_iKGmUK3YEd6pn5gd7VEuBA referencedTable=Package
  `alias` VARCHAR(255), # columnId=_iJgJYK3YEd6pn5gd7VEuBA 
  `status` VARCHAR(255), # columnId=_iJgJZ63YEd6pn5gd7VEuBA 
  `author` VARCHAR(255), # columnId=_iJp6YK3YEd6pn5gd7VEuBA 
  `version` VARCHAR(255), # columnId=_iJp6Zq3YEd6pn5gd7VEuBA 
  `name` VARCHAR(255), # columnId=_iJp6ba3YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_iJp6dK3YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_iJp6e63YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_iJzEVq3YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_iJzEXa3YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_iJzEZK3YEd6pn5gd7VEuBA 
  `sortkey` INT(11),
  PRIMARY KEY (`id`)
  ,KEY `fk_package_id` (`fk_package_id`)
) TYPE=MyISAM;
#
# Structure of Table `ChiNodeManyToMany`
# A many to many node used in Chronos. It is used to realize a many to many relation between two ChiNodes.
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `ChiNodeManyToMany`;
CREATE TABLE `ChiNodeManyToMany` # entityType=ChiNodeManyToMany tableId={8C3C829B-A5B8-4e6c-91C2-7877ED6DE1F1}
(
  `id` INT(11) NOT NULL, # columnId=_iPKsiq3YEd6pn5gd7VEuBA 
  `fk_chicontroller_id` INT(11), # columnId=_iPKsha3YEd6pn5gd7VEuBA referencedTable=ChiController
  `fk_package_id` INT(11), # columnId=_iPKsgK3YEd6pn5gd7VEuBA referencedTable=Package
  `display_value` VARCHAR(255), # columnId=_iORUqq3YEd6pn5gd7VEuBA 
  `parent_order` VARCHAR(255), # columnId=_iORUsa3YEd6pn5gd7VEuBA 
  `child_order` VARCHAR(255), # columnId=_iORUuK3YEd6pn5gd7VEuBA 
  `pk_name` VARCHAR(255), # columnId=_iObFoK3YEd6pn5gd7VEuBA 
  `is_searchable` VARCHAR(255), # columnId=_iObFp63YEd6pn5gd7VEuBA 
  `orderby` VARCHAR(255), # columnId=_iObFrq3YEd6pn5gd7VEuBA 
  `is_soap` VARCHAR(255), # columnId=_iObFta3YEd6pn5gd7VEuBA 
  `initparams` VARCHAR(255), # columnId=_iObFvK3YEd6pn5gd7VEuBA 
  `table_name` VARCHAR(255), # columnId=_iObFw63YEd6pn5gd7VEuBA 
  `is_ordered` VARCHAR(255), # columnId=_iOkPla3YEd6pn5gd7VEuBA 
  `alias` VARCHAR(255), # columnId=_iOkPm63YEd6pn5gd7VEuBA 
  `status` VARCHAR(255), # columnId=_iOkPoq3YEd6pn5gd7VEuBA 
  `author` VARCHAR(255), # columnId=_iOkPqK3YEd6pn5gd7VEuBA 
  `version` VARCHAR(255), # columnId=_iOuAlK3YEd6pn5gd7VEuBA 
  `name` VARCHAR(255), # columnId=_iOuAm63YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_iOuAoq3YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_iOuAqa3YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_iOuAsK3YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_iOuAt63YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_iOuAvq3YEd6pn5gd7VEuBA 
  PRIMARY KEY (`id`)
  ,KEY `fk_chicontroller_id` (`fk_chicontroller_id`)
  ,KEY `fk_package_id` (`fk_package_id`)
) TYPE=MyISAM;
#
# Structure of Table `ChiValueRef`
# 
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `ChiValueRef`;
CREATE TABLE `ChiValueRef` # entityType=ChiValueRef tableId={7C839F4A-38A4-487c-A1B9-0F662EB23EB7}
(
  `id` INT(11) NOT NULL, # columnId=_i0tpmq3YEd6pn5gd7VEuBA 
  `fk_chinodemanytomany_id` INT(11), # columnId=_i0tpla3YEd6pn5gd7VEuBA referencedTable=ChiNodeManyToMany
  `fk_chinode_id` INT(11), # columnId=_i0tpkK3YEd6pn5gd7VEuBA referencedTable=ChiNode
  `name` VARCHAR(255), # columnId=_i0RksK3YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_i0Rkt63YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_i0Rkvq3YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_i0Rkxa3YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_i0aupq3YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_i0aura3YEd6pn5gd7VEuBA 
  `sortkey` INT(11),
  PRIMARY KEY (`id`)
  ,KEY `fk_chinodemanytomany_id` (`fk_chinodemanytomany_id`)
  ,KEY `fk_chinode_id` (`fk_chinode_id`)
) TYPE=MyISAM;
#
# Structure of Table `Property`
# this class reppresent an UML property
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `Property`;
CREATE TABLE `Property` # entityType=Property tableId={C91AB5D8-147C-4830-9A9A-B60BCCA716C2}
(
  `id` INT(11) NOT NULL, # columnId=_iHuAv63YEd6pn5gd7VEuBA 
  `fk_package_id` INT(11), # columnId=_iHuAuq3YEd6pn5gd7VEuBA referencedTable=Package
  `fk_chicontroller_id` INT(11), # columnId=_iHuAta3YEd6pn5gd7VEuBA referencedTable=ChiController
  `fk_chisystem_id` INT(11), # columnId=_iHuAsK3YEd6pn5gd7VEuBA referencedTable=ChiSystem
  `default` VARCHAR(255), # columnId={FE7C16C2-28BA-4573-A04D-995E2EA4536B} 
  `propertytype` VARCHAR(255), # columnId={537B248B-8525-4b56-BC19-31DC1CEB1866} 
  `alias` VARCHAR(255), # columnId=_iHHjwK3YEd6pn5gd7VEuBA 
  `status` VARCHAR(255), # columnId=_iHHjx63YEd6pn5gd7VEuBA 
  `author` VARCHAR(255), # columnId=_iHHjza3YEd6pn5gd7VEuBA 
  `version` VARCHAR(255), # columnId=_iHHj063YEd6pn5gd7VEuBA 
  `name` VARCHAR(255), # columnId=_iHRUxq3YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_iHRUza3YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_iHRU1K3YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_iHRU263YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_iHRU4q3YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_iHaeta3YEd6pn5gd7VEuBA 
  `sortkey` INT(11),
  PRIMARY KEY (`id`)
  ,KEY `fk_package_id` (`fk_package_id`)
  ,KEY `fk_chicontroller_id` (`fk_chicontroller_id`)
  ,KEY `fk_chisystem_id` (`fk_chisystem_id`)
) TYPE=MyISAM;
#
# Structure of Table `ChiNode`
# A Domain Object type used in Chronos. ChiNodes and ChiValues define the application data model.
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `ChiNode`;
CREATE TABLE `ChiNode` # entityType=ChiNode tableId={8AFE696D-2AAD-4e0d-A928-30389C846838}
(
  `id` INT(11) NOT NULL, # columnId=_iN0ouq3YEd6pn5gd7VEuBA 
  `fk_package_id` INT(11), # columnId=_iN0ota3YEd6pn5gd7VEuBA referencedTable=Package
  `fk_chicontroller_id` INT(11), # columnId=_iN0osK3YEd6pn5gd7VEuBA referencedTable=ChiController
  `display_value` VARCHAR(255), # columnId={AB2B0FEC-CBCD-465b-9D31-6503A09C7741} 
  `parent_order` VARCHAR(255), # columnId={02DEC154-2049-4fb0-901E-1B990421F241} 
  `child_order` VARCHAR(255), # columnId={FB5F7482-861C-4053-B5F3-285F9D01CD94} 
  `pk_name` VARCHAR(255), # columnId={30155F3E-BB5A-40fa-84D1-BD17EABF44D8} 
  `is_searchable` VARCHAR(255), # columnId={65DFFF39-0075-4beb-AD7A-6C97F9527B53} 
  `orderby` VARCHAR(255), # columnId={70012A42-F789-4756-896C-409AC7B493B0} 
  `is_soap` VARCHAR(255), # columnId={9C0E72F3-47AD-4a3d-9D00-31CB1B617B36} 
  `initparams` VARCHAR(255), # columnId={337B081D-5E11-4e73-A08A-16C33B84CCF4} 
  `table_name` VARCHAR(255), # columnId={E3734080-2046-4c10-8CC6-A56250E3D7D8} 
  `is_ordered` VARCHAR(255), # columnId={D7A7A498-5B12-40de-A106-A7B56668C493} 
  `alias` VARCHAR(255), # columnId=_iNOy0K3YEd6pn5gd7VEuBA 
  `status` VARCHAR(255), # columnId=_iNOy163YEd6pn5gd7VEuBA 
  `author` VARCHAR(255), # columnId=_iNOy3a3YEd6pn5gd7VEuBA 
  `version` VARCHAR(255), # columnId=_iNOy463YEd6pn5gd7VEuBA 
  `name` VARCHAR(255), # columnId=_iNX8wa3YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_iNX8yK3YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_iNX8z63YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_iNX81q3YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_iNX83a3YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_iNX85K3YEd6pn5gd7VEuBA 
  `sortkey` INT(11),
  PRIMARY KEY (`id`)
  ,KEY `fk_package_id` (`fk_package_id`)
  ,KEY `fk_chicontroller_id` (`fk_chicontroller_id`)
) TYPE=MyISAM;
#
# Structure of Table `ChiController`
# A ChiController, Views and Associations define the application flow. A controller represent the Business logic where a certain flow is physical implemented.
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `ChiController`;
CREATE TABLE `ChiController` # entityType=ChiController tableId={AF6EF41B-69E6-49d4-ADE9-5BF995414A9E}
(
  `id` INT(11) NOT NULL, # columnId=_iMyG763YEd6pn5gd7VEuBA 
  `fk_chibusinessusecasecore_id` INT(11), # columnId=_iMyG6q3YEd6pn5gd7VEuBA referencedTable=ChiBusinessUseCaseCore
  `fk_package_id` INT(11), # columnId=_iMyG5a3YEd6pn5gd7VEuBA referencedTable=Package
  `fk_chibusinessusecase_id` INT(11), # columnId=_iMyG4K3YEd6pn5gd7VEuBA referencedTable=ChiBusinessUseCase
  `alias` VARCHAR(255), # columnId=_iMLp8K3YEd6pn5gd7VEuBA 
  `status` VARCHAR(255), # columnId=_iMLp963YEd6pn5gd7VEuBA 
  `author` VARCHAR(255), # columnId=_iMLp_a3YEd6pn5gd7VEuBA 
  `version` VARCHAR(255), # columnId=_iMVa9a3YEd6pn5gd7VEuBA 
  `name` VARCHAR(255), # columnId=_iMVa_K3YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_iMVbA63YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_iMVbCq3YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_iMVbEa3YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_iMVbGK3YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_iMVbH63YEd6pn5gd7VEuBA 
  `sortkey` INT(11),
  PRIMARY KEY (`id`)
  ,KEY `fk_chibusinessusecasecore_id` (`fk_chibusinessusecasecore_id`)
  ,KEY `fk_package_id` (`fk_package_id`)
  ,KEY `fk_chibusinessusecase_id` (`fk_chibusinessusecase_id`)
) TYPE=MyISAM;
#
# Structure of Table `ChiView`
# A ChiView is a logical class used to display a ChiNode
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `ChiView`;
CREATE TABLE `ChiView` # entityType=ChiView tableId={8DC5A1D2-AA2C-4d96-9B47-B1C7C93F9DA3}
(
  `id` INT(11) NOT NULL, # columnId=_iLS5L63YEd6pn5gd7VEuBA 
  `fk_chinodemanytomany_id` INT(11), # columnId=_iLS5Kq3YEd6pn5gd7VEuBA referencedTable=ChiNodeManyToMany
  `fk_package_id` INT(11), # columnId=_iLS5Ja3YEd6pn5gd7VEuBA referencedTable=Package
  `fk_chinode_id` INT(11), # columnId=_iLS5IK3YEd6pn5gd7VEuBA referencedTable=ChiNode
  `alias` VARCHAR(255), # columnId=_iKscMK3YEd6pn5gd7VEuBA 
  `status` VARCHAR(255), # columnId=_iKscN63YEd6pn5gd7VEuBA 
  `author` VARCHAR(255), # columnId=_iK2NMq3YEd6pn5gd7VEuBA 
  `version` VARCHAR(255), # columnId=_iK2NOK3YEd6pn5gd7VEuBA 
  `name` VARCHAR(255), # columnId=_iK2NP63YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_iK2NRq3YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_iK2NTa3YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_iK2NVK3YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_iK2NW63YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_iK_XJq3YEd6pn5gd7VEuBA 
  `sortkey` INT(11),
  PRIMARY KEY (`id`)
  ,KEY `fk_chinodemanytomany_id` (`fk_chinodemanytomany_id`)
  ,KEY `fk_package_id` (`fk_package_id`)
  ,KEY `fk_chinode_id` (`fk_chinode_id`)
) TYPE=MyISAM;
#
# Structure of Table `ChiAuthors`
# This class host all the actors actively involved in the project.
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `ChiAuthors`;
CREATE TABLE `ChiAuthors` # entityType=ChiAuthors tableId={5FE413E3-1A62-481e-BA5D-E6DB6DDDF19C}
(
  `id` INT(11) NOT NULL, # columnId=_iz04wK3YEd6pn5gd7VEuBA 
  `role` VARCHAR(255), # columnId={D45593F8-C3B5-402d-B584-D98FE9F5D224} 
  `name` VARCHAR(255), # columnId=_izhWwK3YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_izhWx63YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_izrHxa3YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_izrHzK3YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_izrH063YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_izrH2q3YEd6pn5gd7VEuBA 
  PRIMARY KEY (`id`)
) TYPE=MyISAM;
#
# Structure of Table `ChiValue`
# 
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `ChiValue`;
CREATE TABLE `ChiValue` # entityType=ChiValue tableId={75A961F2-4EE3-452e-B190-A5838FB6879E}
(
  `id` INT(11) NOT NULL, # columnId=_iJW_cK3YEd6pn5gd7VEuBA 
  `fk_chicontroller_id` INT(11), # columnId=_iJNOhK3YEd6pn5gd7VEuBA referencedTable=ChiController
  `fk_chisystem_id` INT(11), # columnId=_iJNOf63YEd6pn5gd7VEuBA referencedTable=ChiSystem
  `fk_chinodemanytomany_id` INT(11), # columnId=_iJNOeq3YEd6pn5gd7VEuBA referencedTable=ChiNodeManyToMany
  `fk_package_id` INT(11), # columnId=_iJNOda3YEd6pn5gd7VEuBA referencedTable=Package
  `fk_chinode_id` INT(11), # columnId=_iJNOcK3YEd6pn5gd7VEuBA referencedTable=ChiNode
  `display_type` VARCHAR(255), # columnId={3C1D47AF-9C23-4926-BBDB-3856E17C5EAB} 
  `restrictions_description` VARCHAR(255), # columnId={444F832E-06E8-4c11-8317-6E34600B51D2} 
  `restrictions_match` VARCHAR(255), # columnId={728EC4AD-A3CE-4071-936C-D54DCE9B87B8} 
  `restrictions_not_match` VARCHAR(255), # columnId={D169B294-EC29-431a-A9A2-3FACF250EE73} 
  `input_type` VARCHAR(255), # columnId={DD64B12A-8440-47f7-A658-78B1985F8045} 
  `app_data_type` VARCHAR(255), # columnId={4EDDF18E-E3FD-49bc-8F4D-6C300DA7D8D7} 
  `db_data_type` VARCHAR(255), # columnId={FF516439-8D2C-43b5-8470-44107939958D} 
  `is_editable` VARCHAR(255), # columnId={DBED7B52-D7BE-44fe-86A2-756232173623} 
  `column_name` VARCHAR(255), # columnId={6DFCB27E-38F0-4661-A7C3-354DE6F2926D} 
  `default` VARCHAR(255), # columnId=_iIdnkK3YEd6pn5gd7VEuBA 
  `propertytype` VARCHAR(255), # columnId=_iImxhq3YEd6pn5gd7VEuBA 
  `alias` VARCHAR(255), # columnId=_iImxja3YEd6pn5gd7VEuBA 
  `status` VARCHAR(255), # columnId=_iImxlK3YEd6pn5gd7VEuBA 
  `author` VARCHAR(255), # columnId=_iImxmq3YEd6pn5gd7VEuBA 
  `version` VARCHAR(255), # columnId=_iImxoK3YEd6pn5gd7VEuBA 
  `name` VARCHAR(255), # columnId=_iImxp63YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_iIwihq3YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_iIwija3YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_iIwilK3YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_iIwim63YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_iIwioq3YEd6pn5gd7VEuBA 
  `sortkey` INT(11),
  PRIMARY KEY (`id`)
  ,KEY `fk_chicontroller_id` (`fk_chicontroller_id`)
  ,KEY `fk_chisystem_id` (`fk_chisystem_id`)
  ,KEY `fk_chinodemanytomany_id` (`fk_chinodemanytomany_id`)
  ,KEY `fk_package_id` (`fk_package_id`)
  ,KEY `fk_chinode_id` (`fk_chinode_id`)
) TYPE=MyISAM;
#
# Structure of Table `DisplayType`
# list all the allowed display types (e.g image, text, links)
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `DisplayType`;
CREATE TABLE `DisplayType` # entityType=DisplayType tableId={F8F7E11B-5F40-4c0e-8CCE-5F1D2BF744C0}
(
  `id` INT(11) NOT NULL, # columnId=_izOb0K3YEd6pn5gd7VEuBA 
  `name` VARCHAR(255), # columnId=_iy7g4K3YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_iy7g563YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_iy7g7q3YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_iy7g9a3YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_iy7g_K3YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_iy7hA63YEd6pn5gd7VEuBA 
  PRIMARY KEY (`id`)
) TYPE=MyISAM;
#
# Structure of Table `InputType`
# this class hosts all the allowed input types like text, password, textarea, select, radio, checkbox, file, fileex, fckeditor, filebrowser, linkbrowser, date ...
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `InputType`;
CREATE TABLE `InputType` # entityType=InputType tableId={63AAFE45-872D-47ea-B68D-2169AED993BC}
(
  `id` INT(11) NOT NULL, # columnId=_iye08K3YEd6pn5gd7VEuBA 
  `name` VARCHAR(255), # columnId=_iyL6AK3YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_iyL6B63YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_iyVD9a3YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_iyVD_K3YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_iyVEA63YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_iyVECq3YEd6pn5gd7VEuBA 
  PRIMARY KEY (`id`)
) TYPE=MyISAM;
#
# Structure of Table `ChiAssociation`
# this class handle all the relationships between ChiNodes.
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `ChiAssociation`;
CREATE TABLE `ChiAssociation` # entityType=ChiAssociation tableId={405DFC7B-B07F-4af1-90D8-F1E0254E0683}
(
  `id` INT(11) NOT NULL, # columnId=_iq4YJa3YEd6pn5gd7VEuBA 
  `fk_chinodemanytomany_id` INT(11), # columnId=_iq4YIK3YEd6pn5gd7VEuBA referencedTable=ChiNodeManyToMany
  `fk_chinodetarget_id` INT(11), # columnId=_iqvONa3YEd6pn5gd7VEuBA referencedTable=ChiNode
  `fk_chinodesource_id` INT(11), # columnId=_iqvOMK3YEd6pn5gd7VEuBA referencedTable=ChiNode
  `fk_name` VARCHAR(255), # columnId={8467C2E3-AE94-49ef-AFA9-9EE1332B877B} 
  `sourcemultiplicity` VARCHAR(255), # columnId=_iqIxQK3YEd6pn5gd7VEuBA 
  `sourcenavigability` VARCHAR(255), # columnId=_iqSiRK3YEd6pn5gd7VEuBA 
  `targetmultiplicity` VARCHAR(255), # columnId=_iqSiSq3YEd6pn5gd7VEuBA 
  `targetnavigability` VARCHAR(255), # columnId=_iqSiUK3YEd6pn5gd7VEuBA 
  `relationtype` VARCHAR(255), # columnId=_iqSiVq3YEd6pn5gd7VEuBA 
  `name` VARCHAR(255), # columnId=_iqSiXa3YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_iqbsNa3YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_iqbsPK3YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_iqbsQ63YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_iqbsSq3YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_iqbsUa3YEd6pn5gd7VEuBA 
  PRIMARY KEY (`id`)
  ,KEY `fk_chinodemanytomany_id` (`fk_chinodemanytomany_id`)
  ,KEY `fk_chinodetarget_id` (`fk_chinodetarget_id`)
  ,KEY `fk_chinodesource_id` (`fk_chinodesource_id`)
) TYPE=MyISAM;
#
# Structure of Table `Operation`
# 
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `Operation`;
CREATE TABLE `Operation` # entityType=Operation tableId={451BF687-0FE7-46f8-8D36-B4BFC8615200}
(
  `id` INT(11) NOT NULL, # columnId=_ix4_EK3YEd6pn5gd7VEuBA 
  `fk_chinodemanytomany_id` INT(11), # columnId=_ixvOGq3YEd6pn5gd7VEuBA referencedTable=ChiNodeManyToMany
  `fk_chicontroller_id` INT(11), # columnId=_ixvOFa3YEd6pn5gd7VEuBA referencedTable=ChiController
  `fk_chinode_id` INT(11), # columnId=_ixvOEK3YEd6pn5gd7VEuBA referencedTable=ChiNode
  `returntype` VARCHAR(255), # columnId={E142B703-5D7D-49f7-BDDC-2B09283FC76F} 
  `parameters` VARCHAR(255), # columnId={F5990616-0021-46d7-B814-9C504849915D} 
  `name` VARCHAR(255), # columnId=_ixSiIK3YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_ixSiJ63YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_ixcTJa3YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_ixcTLK3YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_ixcTM63YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_ixcTOq3YEd6pn5gd7VEuBA 
  `sortkey` INT(11),
  PRIMARY KEY (`id`)
  ,KEY `fk_chinodemanytomany_id` (`fk_chinodemanytomany_id`)
  ,KEY `fk_chicontroller_id` (`fk_chicontroller_id`)
  ,KEY `fk_chinode_id` (`fk_chinode_id`)
) TYPE=MyISAM;
#
# Structure of Table `Relation`
# 
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `Relation`;
CREATE TABLE `Relation` # entityType=Relation tableId={20323138-F43B-4773-BB96-4875BDE44258}
(
  `id` INT(11) NOT NULL, # columnId=_ip12UK3YEd6pn5gd7VEuBA 
  `sourcemultiplicity` VARCHAR(255), # columnId={B767CD4B-B81F-466c-844C-C8EDD3CDF1C9} 
  `sourcenavigability` VARCHAR(255), # columnId={CC14CC19-5414-4176-B174-8417CB6EF689} 
  `targetmultiplicity` VARCHAR(255), # columnId={E4D1A54A-018F-4165-B7AB-BCD58A9E279A} 
  `targetnavigability` VARCHAR(255), # columnId={C20736E0-237A-48de-833D-5FAD37EFCB63} 
  `relationtype` VARCHAR(255), # columnId={CC44FC1C-9555-480f-8803-BCE70B993882} 
  `name` VARCHAR(255), # columnId=_ipi7YK3YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_ipi7Z63YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_ipi7bq3YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_ipi7da3YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_ipi7fK3YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_ipi7g63YEd6pn5gd7VEuBA 
  PRIMARY KEY (`id`)
) TYPE=MyISAM;
#
# Structure of Table `RelationMultiplicity`
# this class contains all the multiplicities that are supported by a relation.
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `RelationMultiplicity`;
CREATE TABLE `RelationMultiplicity` # entityType=RelationMultiplicity tableId={19920985-F608-470c-958F-4603868753A1}
(
  `id` INT(11) NOT NULL, # columnId=_ipGPcK3YEd6pn5gd7VEuBA 
  `name` VARCHAR(255), # columnId=_ioytcK3YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_io8edK3YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_io8ee63YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_io8egq3YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_io8eia3YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_io8ekK3YEd6pn5gd7VEuBA 
  PRIMARY KEY (`id`)
) TYPE=MyISAM;
#
# Structure of Table `RelationType`
# this class host all the relations type hosted by relation. Like Generalizzation, realization, aggregation, composition, etc.
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `RelationType`;
CREATE TABLE `RelationType` # entityType=RelationType tableId={CB8E5BEF-5029-4d5a-9245-CE53720891C2}
(
  `id` INT(11) NOT NULL, # columnId=_iofygK3YEd6pn5gd7VEuBA 
  `name` VARCHAR(255), # columnId=_ioM3kK3YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_ioM3l63YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_ioM3nq3YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_ioWolq3YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_ioWona3YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_ioWopK3YEd6pn5gd7VEuBA 
  PRIMARY KEY (`id`)
) TYPE=MyISAM;
#
# Structure of Table `ChiBaseStatus`
# this classes describes stati that are general valid for all ChiObjects. Special stati enumeration are describes in separates enumeration entities.
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `ChiBaseStatus`;
CREATE TABLE `ChiBaseStatus` # entityType=ChiBaseStatus tableId={5C537B68-52B7-4997-B7B2-5682DBA1A72D}
(
  `id` INT(11) NOT NULL, # columnId=_in58oK3YEd6pn5gd7VEuBA 
  `name` VARCHAR(255), # columnId=_inmaoK3YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_inmap63YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_inmarq3YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_inmata3YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_inmavK3YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_inwLpq3YEd6pn5gd7VEuBA 
  PRIMARY KEY (`id`)
) TYPE=MyISAM;
#
# Structure of Table `Counter`
# the class counter hosts counter properties for all the objects actually supportedby the system.
# This class is a single tone and exisst only one time in each CWM instance.
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `Counter`;
CREATE TABLE `Counter` # entityType=Counter tableId={F256DAC9-7123-4b7c-B39E-6D223FB0562B}
(
  `id` INT(11) NOT NULL, # columnId=_i5Vq4K3YEd6pn5gd7VEuBA 
  `chigoal` VARCHAR(255), # columnId={BCC61546-3C3B-4b02-BDEF-7707F51E8F3F} 
  `chirequirement` VARCHAR(255), # columnId={A5CA5BE7-45A8-4f1d-8D35-1B186B72A787} 
  `chifeature` VARCHAR(255), # columnId={20100C68-5931-4ad9-BB61-57A2AD0E5C90} 
  `chiissue` VARCHAR(255), # columnId={B0CF6DC3-73FA-46ce-95BA-D4D4F96DA400} 
  `chibusinessusecase` VARCHAR(255), # columnId={F838E3A6-4156-4196-8EF4-C134BB098181} 
  `chibusinessprocess` VARCHAR(255), # columnId={FA5A3462-BCB0-4e37-9C9C-EC0429018AF0} 
  `chibusinessusecasecore` VARCHAR(255), # columnId={F8597BE1-62CD-4c0f-9312-E6559CFEE7F9} 
  `chibusinesspartneractive` VARCHAR(255), # columnId={CA42116B-59E5-417e-A6D2-2015B3888A08} 
  `chibusinesspartnerpassive` VARCHAR(255), # columnId={EB3902DA-1C3A-4717-8572-993E38FBFF21} 
  `chiworkerexternal` VARCHAR(255), # columnId={646530F4-5F44-46ef-A9B1-23967DB3C893} 
  `chiworkerinternal` VARCHAR(255), # columnId={940F07A8-88B6-4041-B3F2-58514BC24EA3} 
  `chiworker` VARCHAR(255), # columnId={B6A2533D-F959-49aa-94D7-5B3F820C902D} 
  `chibusinesspartner` VARCHAR(255), # columnId={AA06C7AB-19C9-4ce6-A5D9-DEA2723109AC} 
  `chicontroller` VARCHAR(255), # columnId={62EE73B3-651C-4952-9DFD-19B7F17359C5} 
  `chinode` VARCHAR(255), # columnId={C29B839E-0EBA-4753-9CA6-0694E32CD022} 
  `chivalue` VARCHAR(255), # columnId={17C743DB-EE2B-4c4a-B0E3-B394CC45EB37} 
  `chiview` VARCHAR(255), # columnId={CFEFB62C-41FC-4124-9E74-A286C46CD2F0} 
  `operation` VARCHAR(255), # columnId={F3186679-039D-436f-8CEF-99622A1A0429} 
  `activity` VARCHAR(255), # columnId={62259A85-9358-4b94-AA72-71D3B80E4700} 
  `activitydecision` VARCHAR(255), # columnId={4AD017D8-E292-4e06-8123-0BF6D7D7D803} 
  `activityreceive` VARCHAR(255), # columnId={B32CD410-0F92-43f4-A84C-F7DE1FD67542} 
  `activitysend` VARCHAR(255), # columnId={2CC53712-7C92-4b94-94A0-40AA4C1CA8E3} 
  `activityinitial` VARCHAR(255), # columnId={2C3F6274-DE08-49c5-8E4A-D14C0BCBACA2} 
  `activityfinal` VARCHAR(255), # columnId={CC70429E-F149-485f-ADE9-F4FB339004FB} 
  `chisystem` VARCHAR(255), # columnId={68687D01-3B5D-4af4-9EC7-E99D563D06B0} 
  `created` VARCHAR(255), # columnId=_i5L54K3YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_i5L5563YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_i5L57q3YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_i5L59a3YEd6pn5gd7VEuBA 
  PRIMARY KEY (`id`)
) TYPE=MyISAM;
#
# Structure of Table `History`
# 
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `History`;
CREATE TABLE `History` # entityType=History tableId={7215C188-C704-4563-9F4B-A33F45EE4D53}
(
  `id` INT(11) NOT NULL, # columnId=_i6FRwK3YEd6pn5gd7VEuBA 
  `data` TEXT, # columnId={50CD49AE-4A65-49c0-953A-8327E9DBB46D} 
  `duplicate` BOOLEAN, # columnId={2A8E41F7-D413-4600-8A29-1E1217F91555} 
  `eventtype` ENUM('create','delete','changeProperty','associate','disassociate'), # columnId={95684D7D-9388-444a-8C21-B291F9A49782} 
  `affectedoid` VARCHAR(255), # columnId={B130F069-6FDA-4959-A729-D8A403DDDB2D} 
  `otheroid` VARCHAR(255), # columnId={44F97975-E831-4333-9223-25D0E106CC00} 
  `timestamp` BIGINT, # columnId={EB97A920-A00F-4e6f-9FE7-D8DF7FB7108A} 
  `user` VARCHAR(255), # columnId={79BB85A7-A52F-409e-8AFE-ACD87F90D5C7} 
  PRIMARY KEY (`id`)
) TYPE=MyISAM;
#
# Structure of Table `Language`
# A llanguage for which a translation of the model can be created. The code is arbitrary but it is recommended to use the ISO language codes (en, de, it, ...).
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `Language`;
CREATE TABLE `Language` # entityType=Language tableId={279AE4E5-852E-4b71-A8B4-C1E5E220D600}
(
  `id` INT(11) NOT NULL, # columnId=_inTfsK3YEd6pn5gd7VEuBA 
  `code` VARCHAR(255), # columnId={B6B7AE1F-487C-4180-8A26-6F4E1549FB3B} 
  `name` VARCHAR(255), # columnId=_inAkwK3YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_inAkx63YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_inAkzq3YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_inAk1a3YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_inAk3K3YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_inAk463YEd6pn5gd7VEuBA 
  PRIMARY KEY (`id`)
) TYPE=MyISAM;
#
# Structure of Table `Figure`
# A figure is the graphical reppresentation of a node can be linked with manies diagrams.
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `Figure`;
CREATE TABLE `Figure` # entityType=Figure tableId={7A186367-446B-4fab-9CA9-20ADC1531450}
(
  `id` INT(11) NOT NULL, # columnId=_h8Y6eq3YEd6pn5gd7VEuBA 
  `fk_chiobject_id` INT(11), # columnId=_h8Y6da3YEd6pn5gd7VEuBA referencedTable=ChiObject
  `fk_activity_id` INT(11), # columnId=_h8Y6cK3YEd6pn5gd7VEuBA referencedTable=Activity
  `fk_activitydecision_id` INT(11), # columnId=_h8PwlK3YEd6pn5gd7VEuBA referencedTable=ActivityDecision
  `fk_activityreceive_id` INT(11), # columnId=_h8Pwj63YEd6pn5gd7VEuBA referencedTable=ActivityReceive
  `fk_activitysend_id` INT(11), # columnId=_h8Pwiq3YEd6pn5gd7VEuBA referencedTable=ActivitySend
  `fk_activityinitial_id` INT(11), # columnId=_h8Pwha3YEd6pn5gd7VEuBA referencedTable=ActivityInitial
  `fk_activityfinal_id` INT(11), # columnId=_h8PwgK3YEd6pn5gd7VEuBA referencedTable=ActivityFinal
  `fk_chisystem_id` INT(11), # columnId=_h8F_lK3YEd6pn5gd7VEuBA referencedTable=ChiSystem
  `fk_chiworkerexternal_id` INT(11), # columnId=_h8F_j63YEd6pn5gd7VEuBA referencedTable=ChiWorkerExternal
  `fk_chiworkerinternal_id` INT(11), # columnId=_h8F_iq3YEd6pn5gd7VEuBA referencedTable=ChiWorkerInternal
  `fk_chiworker_id` INT(11), # columnId=_h8F_ha3YEd6pn5gd7VEuBA referencedTable=ChiWorker
  `fk_chibusinesspartneractive_id` INT(11), # columnId=_h8F_gK3YEd6pn5gd7VEuBA referencedTable=ChiBusinessPartnerActive
  `fk_chibusinesspartnerpassive_id` INT(11), # columnId=_h78Oma3YEd6pn5gd7VEuBA referencedTable=ChiBusinessPartnerPassive
  `fk_chibusinesspartner_id` INT(11), # columnId=_h78OlK3YEd6pn5gd7VEuBA referencedTable=ChiBusinessPartner
  `fk_actor_id` INT(11), # columnId=_h78Oj63YEd6pn5gd7VEuBA referencedTable=Actor
  `fk_chibusinessprocess_id` INT(11), # columnId=_h78Oiq3YEd6pn5gd7VEuBA referencedTable=ChiBusinessProcess
  `fk_chibusinessusecasecore_id` INT(11), # columnId=_h78Oha3YEd6pn5gd7VEuBA referencedTable=ChiBusinessUseCaseCore
  `fk_chibusinessusecase_id` INT(11), # columnId=_h78OgK3YEd6pn5gd7VEuBA referencedTable=ChiBusinessUseCase
  `fk_chigoal_id` INT(11), # columnId=_h7zEqa3YEd6pn5gd7VEuBA referencedTable=ChiGoal
  `fk_chirequirement_id` INT(11), # columnId=_h7zEpK3YEd6pn5gd7VEuBA referencedTable=ChiRequirement
  `fk_chifeature_id` INT(11), # columnId=_h7zEn63YEd6pn5gd7VEuBA referencedTable=ChiFeature
  `fk_chiissue_id` INT(11), # columnId=_h7zEmq3YEd6pn5gd7VEuBA referencedTable=ChiIssue
  `fk_chinodemanytomany_id` INT(11), # columnId=_h7zEla3YEd6pn5gd7VEuBA referencedTable=ChiNodeManyToMany
  `fk_chinode_id` INT(11), # columnId=_h7zEkK3YEd6pn5gd7VEuBA referencedTable=ChiNode
  `fk_chicontroller_id` INT(11), # columnId=_h7pTn63YEd6pn5gd7VEuBA referencedTable=ChiController
  `fk_chiview_id` INT(11), # columnId=_h7pTmq3YEd6pn5gd7VEuBA referencedTable=ChiView
  `fk_chiclass_id` INT(11), # columnId=_h7pTla3YEd6pn5gd7VEuBA referencedTable=ChiClass
  `fk_chivalue_id` INT(11), # columnId=_h7pTkK3YEd6pn5gd7VEuBA referencedTable=ChiValue
  `fk_property_id` INT(11), # columnId=_h7fipK3YEd6pn5gd7VEuBA referencedTable=Property
  `fk_glossary_id` INT(11), # columnId=_h7fin63YEd6pn5gd7VEuBA referencedTable=Glossary
  `fk_diagram_id` INT(11), # columnId=_h7fimq3YEd6pn5gd7VEuBA referencedTable=Diagram
  `fk_chibase_id` INT(11), # columnId=_h7fila3YEd6pn5gd7VEuBA referencedTable=ChiBase
  `fk_activityset_id` INT(11), # columnId=_h7fikK3YEd6pn5gd7VEuBA referencedTable=ActivitySet
  `backgroundcolor` VARCHAR(255), # columnId={6077E09C-AE54-4ebb-BBEF-15B9DFEBFA97} 
  `foregroundcolor` VARCHAR(255), # columnId={C44AF534-BE12-4f51-B06B-3E75C11A3F4A} 
  `gid` VARCHAR(255), # columnId={4B291134-0BC8-41df-BD0B-96E770CB8741} 
  `height` VARCHAR(255), # columnId={5FEC0C75-A1DB-4fa5-B8DA-8A3D0A6CD66B} 
  `positiony` VARCHAR(255), # columnId={4947C61E-996C-471a-B72B-4DB80DF44C6B} 
  `positionx` VARCHAR(255), # columnId={DBD27EEA-B85C-43b6-9DE9-B93EE38F2E1A} 
  `width` VARCHAR(255), # columnId={C6A5D90E-E5BF-4def-8357-7A667348C2C6} 
  `created` VARCHAR(255), # columnId=_h7DdsK3YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_h7Ddt63YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_h7Ddvq3YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_h7Ddxa3YEd6pn5gd7VEuBA 
  PRIMARY KEY (`id`)
  ,KEY `fk_chiobject_id` (`fk_chiobject_id`)
  ,KEY `fk_activity_id` (`fk_activity_id`)
  ,KEY `fk_activitydecision_id` (`fk_activitydecision_id`)
  ,KEY `fk_activityreceive_id` (`fk_activityreceive_id`)
  ,KEY `fk_activitysend_id` (`fk_activitysend_id`)
  ,KEY `fk_activityinitial_id` (`fk_activityinitial_id`)
  ,KEY `fk_activityfinal_id` (`fk_activityfinal_id`)
  ,KEY `fk_chisystem_id` (`fk_chisystem_id`)
  ,KEY `fk_chiworkerexternal_id` (`fk_chiworkerexternal_id`)
  ,KEY `fk_chiworkerinternal_id` (`fk_chiworkerinternal_id`)
  ,KEY `fk_chiworker_id` (`fk_chiworker_id`)
  ,KEY `fk_chibusinesspartneractive_id` (`fk_chibusinesspartneractive_id`)
  ,KEY `fk_chibusinesspartnerpassive_id` (`fk_chibusinesspartnerpassive_id`)
  ,KEY `fk_chibusinesspartner_id` (`fk_chibusinesspartner_id`)
  ,KEY `fk_actor_id` (`fk_actor_id`)
  ,KEY `fk_chibusinessprocess_id` (`fk_chibusinessprocess_id`)
  ,KEY `fk_chibusinessusecasecore_id` (`fk_chibusinessusecasecore_id`)
  ,KEY `fk_chibusinessusecase_id` (`fk_chibusinessusecase_id`)
  ,KEY `fk_chigoal_id` (`fk_chigoal_id`)
  ,KEY `fk_chirequirement_id` (`fk_chirequirement_id`)
  ,KEY `fk_chifeature_id` (`fk_chifeature_id`)
  ,KEY `fk_chiissue_id` (`fk_chiissue_id`)
  ,KEY `fk_chinodemanytomany_id` (`fk_chinodemanytomany_id`)
  ,KEY `fk_chinode_id` (`fk_chinode_id`)
  ,KEY `fk_chicontroller_id` (`fk_chicontroller_id`)
  ,KEY `fk_chiview_id` (`fk_chiview_id`)
  ,KEY `fk_chiclass_id` (`fk_chiclass_id`)
  ,KEY `fk_chivalue_id` (`fk_chivalue_id`)
  ,KEY `fk_property_id` (`fk_property_id`)
  ,KEY `fk_glossary_id` (`fk_glossary_id`)
  ,KEY `fk_diagram_id` (`fk_diagram_id`)
  ,KEY `fk_chibase_id` (`fk_chibase_id`)
  ,KEY `fk_activityset_id` (`fk_activityset_id`)
) TYPE=MyISAM;
#
# Structure of Table `Model`
# a model is the start of the Chronos onthology tree.
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `Model`;
CREATE TABLE `Model` # entityType=Model tableId={B92F55CA-30CA-468d-9088-A1880481B6C2}
(
  `id` INT(11) NOT NULL, # columnId=_iFLqEK3YEd6pn5gd7VEuBA 
  `name` VARCHAR(255), # columnId=_iFB5EK3YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_iFB5F63YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_iFB5Hq3YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_iFB5Ja3YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_iFB5LK3YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_iFB5M63YEd6pn5gd7VEuBA 
  `sortkey` INT(11),
  PRIMARY KEY (`id`)
) TYPE=MyISAM;
#
# Structure of Table `Package`
# a package is a class that contains other classes including packages sef
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `Package`;
CREATE TABLE `Package` # entityType=Package tableId={05C9EAF6-8B0B-44f9-AED7-CBC223C935FB}
(
  `id` INT(11) NOT NULL, # columnId=_iEu-Kq3YEd6pn5gd7VEuBA 
  `fk_package_id` INT(11), # columnId=_iEu-Ja3YEd6pn5gd7VEuBA referencedTable=Package
  `fk_model_id` INT(11), # columnId=_iEu-IK3YEd6pn5gd7VEuBA referencedTable=Model
  `name` VARCHAR(255), # columnId=_iEJIQK3YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_iESSNa3YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_iESSPK3YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_iESSQ63YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_iESSSq3YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_iESSUa3YEd6pn5gd7VEuBA 
  `sortkey` INT(11),
  PRIMARY KEY (`id`)
  ,KEY `fk_package_id` (`fk_package_id`)
  ,KEY `fk_model_id` (`fk_model_id`)
) TYPE=MyISAM;
#
# Structure of Table `Diagram`
# 
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `Diagram`;
CREATE TABLE `Diagram` # entityType=Diagram tableId={F6E80A6E-A203-4fb4-9DD0-FE227031ADD1}
(
  `id` INT(11) NOT NULL, # columnId=_h9lNRa3YEd6pn5gd7VEuBA 
  `fk_package_id` INT(11), # columnId=_h9lNQK3YEd6pn5gd7VEuBA referencedTable=Package
  `width` VARCHAR(255), # columnId={C920C9C4-4CD6-451c-BA0C-F79F4065D67D} 
  `height` VARCHAR(255), # columnId={C44650C8-6BA5-4129-A77E-A2D7D2B3983B} 
  `name` VARCHAR(255), # columnId=_h8_XYK3YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_h9IhVq3YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_h9IhXa3YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_h9IhZK3YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_h9Iha63YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_h9Ihcq3YEd6pn5gd7VEuBA 
  `sortkey` INT(11),
  PRIMARY KEY (`id`)
  ,KEY `fk_package_id` (`fk_package_id`)
) TYPE=MyISAM;
#
# Structure of Table `Glossary`
# 
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `Glossary`;
CREATE TABLE `Glossary` # entityType=Glossary tableId={12BB51F6-4466-4348-A07B-A92AFEAE3C00}
(
  `id` INT(11) NOT NULL, # columnId=_iG0o1a3YEd6pn5gd7VEuBA 
  `fk_package_id` INT(11), # columnId=_iG0o0K3YEd6pn5gd7VEuBA referencedTable=Package
  `entrytype` VARCHAR(255), # columnId={80F23887-760D-4bb4-A22C-60D0534F46BF} 
  `alias` VARCHAR(255), # columnId=_iGOL4K3YEd6pn5gd7VEuBA 
  `status` VARCHAR(255), # columnId=_iGOL563YEd6pn5gd7VEuBA 
  `author` VARCHAR(255), # columnId=_iGOL7a3YEd6pn5gd7VEuBA 
  `version` VARCHAR(255), # columnId=_iGX8463YEd6pn5gd7VEuBA 
  `name` VARCHAR(255), # columnId=_iGX86q3YEd6pn5gd7VEuBA 
  `notes` TEXT, # columnId=_iGX88a3YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_iGX8-K3YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_iGX8_63YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_iGht5a3YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_iGht7K3YEd6pn5gd7VEuBA 
  PRIMARY KEY (`id`)
  ,KEY `fk_package_id` (`fk_package_id`)
) TYPE=MyISAM;
#
# Structure of Table `NMFiguresDiagram`
# 
# version 1.0
# init params database
#
DROP TABLE IF EXISTS `NMFiguresDiagram`;
CREATE TABLE `NMFiguresDiagram` # entityType=NMFiguresDiagram tableId={466BBC51-15B0-4a62-ACC9-433587D48B91}
(
  `id` INT(11) NOT NULL, # columnId=_h1PJkK3YEd6pn5gd7VEuBA 
  `created` VARCHAR(255), # columnId=_h0ydoK3YEd6pn5gd7VEuBA 
  `creator` VARCHAR(255), # columnId=_h0ydp63YEd6pn5gd7VEuBA 
  `last_editor` VARCHAR(255), # columnId=_h08Opq3YEd6pn5gd7VEuBA 
  `modified` VARCHAR(255), # columnId=_h08Ora3YEd6pn5gd7VEuBA 
  PRIMARY KEY (`id`)
) TYPE=MyISAM;
