/*
 *  This file was generated by wCMFGenerator 3.0.0 from src/requirements.uml on Mon Jan 12 18:09:59 CET 2009. 
  Manual modifications should be placed inside the protected regions.
 * Copyright (c) 2009 The Olympos Development Team.
 *
 * http://sourceforge.net/projects/olympos/
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html. If redistributing this code,
 * this entire header must remain intact.
 */
Ext.namespace("cwm");

cwm.ChiBusinessUseCaseCoreClass = function() {
	cwm.ChiBusinessUseCaseCoreClass.superclass.constructor.call(this);
	
	this.uwmClassName = "ChiBusinessUseCaseCore";
	this.instanceClassName = "cwm.ChiBusinessUseCaseCore";
	this.treeIcon = "FigureChiBusinessUseCaseCore";
	this.figureIcon = "FigureChiBusinessUseCaseCore";
	this.figureClass = "uwm.graphics.figure.RectangleFigure";
	this.description = " A Core Use Case generates a value for an active business partner and is directly connected to the objectives (ChiGoals) of a company or the process of his existence (typically making money).";
	this.helpUrl = "help/index.html#ChiBusinessUseCaseCore|outline";
	this.defaultLabel = "New ChiBusinessUseCaseCore";
	this.labelProperties = {
		Name: true
	};

	this.gridTabIconClass = "ChiBusinessUseCaseCoreTab";
	this.gridTabTip = "Shows all <b>ChiBusinessUseCaseCore</b> within selected scope";
	this.gridFields = [{
		name: "oid",
		mapping: "oid"
	}, {
		name: "Label",
		mapping: "Label"
	}];
	this.gridColumns = [{
		header: "Label",
		dataIndex: "Label",
		sortable: true
	}];
	
	this.connectionInfo = {
			
		
		"NMUCActor": {
			label: "",
			invert: true,
			connectionType: 'aggregation'
		}		,				
		"Figure": {
			label: "",
			invert: true,
			connectionType: 'aggregation'
		}					, 								"ChiBusinessProcess": {
			label: "",
			invert: true,
			connectionType:  'association'
		}
	
		,					"Package": {
			label: "",
			invert: true,
			connectionType:  'association'
		}
	

	};
}

Ext.extend(cwm.ChiBusinessUseCaseCoreClass, uwm.model.ModelClass);

cwm.ChiBusinessUseCaseCoreClass.prototype.getPropertyForm = function(modelNode) {
	return new uwm.ui.PropertyForm({
		items: [	,	,	,	new uwm.ui.ComboBox({
fieldLabel: 'PrimaryActor',
			name: 'PrimaryActor',
			modelNode: modelNode,
		}) 
,	new uwm.ui.TextField({
fieldLabel: 'OtherActors',
			name: 'OtherActors',
			modelNode: modelNode,
		}) 
,	new uwm.ui.TextField({
fieldLabel: 'GoalInContext',
			name: 'GoalInContext',
			modelNode: modelNode,
		}) 
,	new uwm.ui.TextField({
fieldLabel: 'Scope',
			name: 'Scope',
			modelNode: modelNode,
		}) 
,	new uwm.ui.TextField({
fieldLabel: 'Level',
			name: 'Level',
			modelNode: modelNode,
		}) 
,	new uwm.ui.TextField({
fieldLabel: 'Stakeholders',
			name: 'Stakeholders',
			modelNode: modelNode,
		}) 
,	new uwm.ui.TextField({
fieldLabel: 'Precondition',
			name: 'Precondition',
			modelNode: modelNode,
		}) 
,	new uwm.ui.TextField({
fieldLabel: 'Trigger',
			name: 'Trigger',
			modelNode: modelNode,
		}) 
,	new uwm.ui.TextField({
fieldLabel: 'MainSuccessScenario',
			name: 'MainSuccessScenario',
			modelNode: modelNode,
		}) 
,	new uwm.ui.TextField({
fieldLabel: 'Extensions',
			name: 'Extensions',
			modelNode: modelNode,
		}) 
,	new uwm.ui.TextField({
fieldLabel: 'Alias',
			name: 'Alias',
			modelNode: modelNode,
		}) 
,	new uwm.ui.TextField({
fieldLabel: 'Version',
			name: 'Version',
			modelNode: modelNode,
		}) 
,	new uwm.ui.TextField({
fieldLabel: 'Name',
			name: 'Name',
			modelNode: modelNode,
		}) 
,	new uwm.ui.HtmlEditor({
fieldLabel: 'Notes',
			name: 'Notes',
			modelNode: modelNode,
		}) 
,	new uwm.ui.TextField({
fieldLabel: 'created',
			name: 'created',
			modelNode: modelNode,
			readOnly: true		}) 
,	new uwm.ui.TextField({
fieldLabel: 'creator',
			name: 'creator',
			modelNode: modelNode,
			readOnly: true		}) 
,	new uwm.ui.TextField({
fieldLabel: 'last_editor',
			name: 'last_editor',
			modelNode: modelNode,
			readOnly: true		}) 
,	new uwm.ui.TextField({
fieldLabel: 'modified',
			name: 'modified',
			modelNode: modelNode,
			readOnly: true		}) 
]
	});
}

cwm.ChiBusinessUseCaseCoreClass.prototype.getGraphics = function(label, figure) {
	return new uwm.graphics.figure.ImageFigure(label, figure, "../application/images/ChiBusinessUseCaseCore.PNG", 96, 95, 96, 95);
}

uwm.model.ModelNodeClassContainer.getInstance().registerClass(new cwm.ChiBusinessUseCaseCoreClass());

	