
// PROTECTED REGION ID(application/gui/js/cwm/UserRDBClass.js/declaration) START
/*
 This file was generated by wCMFGenerator 2.6.1.0031 from model/requirements.xmi on 30.12.08 12:38.
 Manual modifications should be placed inside the protected regions.
 developer: <ingo@wemove.com>
 Version: 1.0
 Class: UserRDB.Class.class.js
 Description:
 * Copyright (c) 2008 The Olympos Development Team.
 *
 * http://sourceforge.net/projects/olympos/
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html. If redistributing this code,
 * this entire header must remain intact.
 */
Ext.namespace("cwm");

cwm.UserRDB = function(modelNodeClass) {
	cwm.UserRDB.superclass.constructor.call(this, modelNodeClass);
}

Ext.extend(cwm.UserRDB, uwm.model.TechnicalObject);

cwm.UserRDB.prototype.initByDisplayResult = function(node) {
	cwm.UserRDB.superclass.initByDisplayResult.call(this, node);
	
	this.data.login = node.values[1].login;
	this.data.password = node.values[1].password;
	this.data.name = node.values[1].name;
	this.data.firstname = node.values[1].firstname;
	//this.data.config = node.values[1].config;
	
}

cwm.UserRDB.prototype.populatePropertyForm = function(form) {
	var realForm = form.getForm();
	
	realForm.findField("login").loadValue(this.data.login);
	realForm.findField("password").loadValue(this.data.password);
	realForm.findField("name").loadValue(this.data.name);
	realForm.findField("firstname").loadValue(this.data.firstname);
	realForm.findField("config").loadValue(this.data.config);
}

cwm.UserRDB.prototype.getGridData = function() {
	return {
		oid: this.getOid(),
		Label: this.getLabel()
	}
}
// PROTECTED REGION END
